<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>3ada407d-63d3-4a11-8c2c-7f69c34a494b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._1m2hr9ge._1m2hr9gd._1fragemsq._1fragemlj._1fragemnk._1fragem2i._1fragems4._1fragemsg._1fragemsl._1fragemsa._1m2hr9g1h._1m2hr9g1d._1fragemne._1m2hr9g16._1m2hr9g13._1fragemop._1fragemon._1fragemor._1fragemol._1fragempl._1fragemph._1fragempp._1fragempd._1fragemb4._1fragemaf._1fragembt._1fragem9q._1fragemsa._1m2hr9g1q._1m2hr9g1o._1m2hr9g10._1m2hr9gx._1m2hr9g1b._1m2hr9g19._1fragems5._1m2hr9g25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Apply Discount Code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>37e02f30-3db0-43c1-bca9-1a26c92ce428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2beec641-1791-4b98-965b-142711ff1e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Apply Discount Code</value>
      <webElementGuid>d7ca8718-7262-44d9-9d32-967593040c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1m2hr9ge _1m2hr9gd _1fragemsq _1fragemlj _1fragemnk _1fragem2i _1fragems4 _1fragemsg _1fragemsl _1fragemsa _1m2hr9g1h _1m2hr9g1d _1fragemne _1m2hr9g16 _1m2hr9g13 _1fragemop _1fragemon _1fragemor _1fragemol _1fragempl _1fragemph _1fragempp _1fragempd _1fragemb4 _1fragemaf _1fragembt _1fragem9q _1fragemsa _1m2hr9g1q _1m2hr9g1o _1m2hr9g10 _1m2hr9gx _1m2hr9g1b _1m2hr9g19 _1fragems5 _1m2hr9g25</value>
      <webElementGuid>8c448d1b-9360-4736-b467-7be0ac201bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>40b42985-1e7b-47c1-9622-c8aa97c602f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form0&quot;)/div[@class=&quot;km09ry1 _1fragemlj&quot;]/div[@class=&quot;_1mrl40q0 _1fragemlj _1fragem2s _1fragem3c _1fragem5p _1fragemm3 _16s97g7f _16s97g7p _16s97g71j _16s97g71t&quot;]/button[@class=&quot;_1m2hr9ge _1m2hr9gd _1fragemsq _1fragemlj _1fragemnk _1fragem2i _1fragems4 _1fragemsg _1fragemsl _1fragemsa _1m2hr9g1h _1m2hr9g1d _1fragemne _1m2hr9g16 _1m2hr9g13 _1fragemop _1fragemon _1fragemor _1fragemol _1fragempl _1fragemph _1fragempp _1fragempd _1fragemb4 _1fragemaf _1fragembt _1fragem9q _1fragemsa _1m2hr9g1q _1m2hr9g1o _1m2hr9g10 _1m2hr9gx _1m2hr9g1b _1m2hr9g19 _1fragems5 _1m2hr9g25&quot;]</value>
      <webElementGuid>4d938f8e-38d7-4efd-8aba-3da5bb24b33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>91023460-1b8d-4c04-9d4e-1d21a70858a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form0']/div/div/button</value>
      <webElementGuid>cb527d75-c99c-4a76-a41a-06ca28f8a8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discount code'])[1]/following::button[1]</value>
      <webElementGuid>2b7d259d-a139-408d-bc92-81d3787a70cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹100.00'])[1]/following::button[1]</value>
      <webElementGuid>10774633-dbc3-4927-af98-2c213ce7cde0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost summary'])[1]/preceding::button[2]</value>
      <webElementGuid>912b7691-40f9-47c5-936f-4f855e048c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/button</value>
      <webElementGuid>c6f160c5-3022-4b0b-81f1-55e370f29176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>9c22f6a2-051c-49e7-b221-dbcaf53fb222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
