<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Security code_card-fields-verificati_0e7a54</name>
   <tag></tag>
   <elementGuidId>2d9ef236-3572-4703-80c5-678d990e6c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-verification_value-29uk9l6h3mi00000']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#card-fields-verification_value-29uk9l6h3mi00000</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-verification_value-29uk9l6h3mi00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>698a0189-3fa9-4a7c-b4c4-ab9448b43d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>c4f4f752-d732-4850-9cf2-a7453e5ce7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7990d16e-a302-4513-a522-535eae822518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-verification_value-29uk9l6h3mi00000</value>
      <webElementGuid>2b2eaad5-bcb8-49bb-ae13-c3e423cd9c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-verification_value-29uk9l6h3mi00000</value>
      <webElementGuid>fed57d99-d321-430a-969e-1cfafebce9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>79286a7a-5206-4f5c-88f7-8269d0d74ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/verification_value?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>b043baec-86d8-4524-979d-fd20d9968d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Security code</value>
      <webElementGuid>5af66adc-9610-4757-85e8-dafc0c4659b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-verification_value-29uk9l6h3mi00000&quot;)</value>
      <webElementGuid>4ba183cc-9be9-4238-b087-2655d5e5d799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-verification_value-29uk9l6h3mi00000']</value>
      <webElementGuid>b79656bb-5bef-4cd5-b02f-f0f3524b3bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='verification_value']/iframe</value>
      <webElementGuid>eabf0730-8dc1-49a1-a8ae-8a1234534d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/iframe</value>
      <webElementGuid>94ce64cc-7904-444c-a458-a90e0040fa91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-verification_value-29uk9l6h3mi00000' and @name = 'card-fields-verification_value-29uk9l6h3mi00000' and @src = 'https://checkout.pci.shopifyinc.com/verification_value?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Security code']</value>
      <webElementGuid>951314d9-06f6-41b7-a8eb-81536d4869b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
