<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Enter a valid card number</name>
   <tag></tag>
   <elementGuidId>f24ef986-40f2-41cf-b563-edbdc40be345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='error-for-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#error-for-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Enter a valid card number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bce2f954-15bf-4c8f-9194-7ef30356f95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>error-for-number</value>
      <webElementGuid>5a095016-7fd5-43ef-953f-bdf428f5e57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ksaxnz0 _1fragemn0</value>
      <webElementGuid>2b600e76-9c98-4240-8727-8ec3d4272561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter a valid card number</value>
      <webElementGuid>1922f2d1-466c-4048-a70a-21375197571c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-for-number&quot;)</value>
      <webElementGuid>d01dfeb4-5740-43f2-93f0-4517bcfc0159</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='error-for-number']</value>
      <webElementGuid>554dc68b-8c14-4e02-9323-6c2027d2945c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='directPaymentMethodDetails']/div/div/div/div/div/div/p</value>
      <webElementGuid>756bea42-472b-4d05-b3a6-fa603d1c02b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card number'])[1]/following::p[1]</value>
      <webElementGuid>9bb38ef6-69c4-4b54-ba76-fffaeec0a4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit card'])[1]/following::p[1]</value>
      <webElementGuid>195e4e66-0b2d-4a48-85d8-10be3755a4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration date (MM / YY)'])[1]/preceding::p[1]</value>
      <webElementGuid>f5fd72fb-9346-4171-a847-bdc5abc50e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security code'])[1]/preceding::p[1]</value>
      <webElementGuid>cd2a9dbe-68d0-486a-b690-93c6c64adf25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter a valid card number']/parent::*</value>
      <webElementGuid>98f27737-f71d-424c-b541-515725551a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/p</value>
      <webElementGuid>c757e872-3b46-4652-a560-883a4047a102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'error-for-number' and (text() = 'Enter a valid card number' or . = 'Enter a valid card number')]</value>
      <webElementGuid>58144ade-4a90-48f4-a801-1a15da2022fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
