<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1042</name>
   <tag></tag>
   <elementGuidId>51cec2eb-3f9e-4459-8951-bc8961033b89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='RowOrder']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RowOrder > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Order number #1042&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50e69175-dd49-465f-85ce-98bd4c050a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://threads0.myshopify.com/account/orders/4f9d654c7681eba83ebaba036f43dfa7</value>
      <webElementGuid>ade92e0d-fced-4990-b3ec-c2b4327d0950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Order number #1042</value>
      <webElementGuid>fbf14a19-fb8c-45a9-8696-be03044fc552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      #1042
                    </value>
      <webElementGuid>82046a6d-49d8-404f-bcac-87e446dc4f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RowOrder&quot;)/a[1]</value>
      <webElementGuid>a720cd50-36b0-4558-92ef-f1fbb64e91f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='RowOrder']/a</value>
      <webElementGuid>3fc3b4a4-78b2-45df-b7a8-476193fe92fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'#1042')]</value>
      <webElementGuid>c7863ec3-edc8-42fb-86f2-d6c8aee4980c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::a[1]</value>
      <webElementGuid>25fc8697-e088-46ea-b3b6-28f5e1d0bf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fulfillment status'])[1]/following::a[1]</value>
      <webElementGuid>ca7abaec-d074-40c7-a9cd-fae6dee673d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='November 3, 2024'])[1]/preceding::a[1]</value>
      <webElementGuid>e5165cb5-1c19-412a-a4ab-04c8eb13c0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paid'])[1]/preceding::a[1]</value>
      <webElementGuid>a7fb3d82-5a88-49e8-ae56-fc8c1d9394a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#1042']/parent::*</value>
      <webElementGuid>eb41c0b3-c9fc-4c17-907f-cdb08da2aa8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://threads0.myshopify.com/account/orders/4f9d654c7681eba83ebaba036f43dfa7')]</value>
      <webElementGuid>3b501d33-e3e9-4e50-8f40-6dc9f921aed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>6f1c998a-125a-472d-8654-e9e680bf4657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://threads0.myshopify.com/account/orders/4f9d654c7681eba83ebaba036f43dfa7' and (text() = '
                      #1042
                    ' or . = '
                      #1042
                    ')]</value>
      <webElementGuid>945ef0f8-ec65-4cfb-8d06-5485ca074b99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
