<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>fb48f641-b047-4b84-acde-8f406e65bf2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.coc-button.coc-cancel-button.coc-cancel-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-template--18610481135839__main']/div/div[2]/div/table/tbody/tr/td[6]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;s] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7e1f5119-ea36-41d3-bc5a-e22b97fd8dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coc-button coc-cancel-button coc-cancel-active</value>
      <webElementGuid>375e6598-d8b6-48a3-9c92-bbadf22366d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-order-id</name>
      <type>Main</type>
      <value>5840969597151</value>
      <webElementGuid>8fb6aa16-0417-45c7-902e-7f42d97df0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>3c04a9a1-78bb-45ea-afe4-e367566b27cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--18610481135839__main&quot;)/div[@class=&quot;customer account section-template--18610481135839__main-padding&quot;]/div[2]/div[1]/table[@class=&quot;order-history&quot;]/tbody[1]/tr[1]/td[6]/div[@class=&quot;coc-d-flex coc-flex-col coc-gap-2 coc-p-1&quot;]/button[@class=&quot;coc-button coc-cancel-button coc-cancel-active&quot;]</value>
      <webElementGuid>e98cd905-dae0-4e57-9e10-eaeb3f33e4d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-template--18610481135839__main']/div/div[2]/div/table/tbody/tr/td[6]/div/button</value>
      <webElementGuid>8662729e-639e-4605-bcf0-02ba05553e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 255.44'])[1]/following::button[1]</value>
      <webElementGuid>7c8187c9-289d-4cf7-90ce-c5d6c808593c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unfulfilled'])[1]/following::button[1]</value>
      <webElementGuid>e6720e2c-ed73-4679-b91d-e3be74969d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reorder'])[1]/preceding::button[1]</value>
      <webElementGuid>b4316650-3d39-4a76-b00b-af3f8a3f4bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#1040'])[1]/preceding::button[2]</value>
      <webElementGuid>5021d2cc-e0df-4156-ab4f-42338fc56650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>15f40214-2a89-4d51-a206-3fa7f04ceb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/button</value>
      <webElementGuid>d789bb60-889f-4003-bab2-c98e52f44955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>bd9bd8ac-1f40-4fe7-b9bc-df1a3c4c95b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
