<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>9c170bda-b9fc-4ae7-9fe9-4b8b332576a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='h-captcha']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Widget containing checkbox for hCaptcha security challenge&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Widget containing checkbox for hCaptcha security challenge&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cd6465e5-c042-41b4-947f-29dc54651ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://newassets.hcaptcha.com/captcha/v1/6416769/static/hcaptcha.html#frame=checkbox&amp;id=09txwjy6j9lb&amp;host=ltopcorner.myshopify.com&amp;sentry=true&amp;reportapi=https%3A%2F%2Faccounts.hcaptcha.com&amp;recaptchacompat=off&amp;custom=false&amp;hl=en&amp;tplinks=on&amp;pstissuer=https%3A%2F%2Fpst-issuer.hcaptcha.com&amp;sitekey=854574d3-241c-4eeb-95cc-896eb71d0349&amp;theme=light&amp;origin=https%3A%2F%2Fltopcorner.myshopify.com</value>
      <webElementGuid>ca006f6c-2adf-4f8e-a641-feadccff7905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>73476d2d-3e91-4120-8028-cade837e7642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da8e0714-6d86-4eea-ae68-72b45d6e7d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8d10e546-8004-4d2b-8527-8cc907386c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>private-state-token-issuance 'src'; private-state-token-redemption 'src'</value>
      <webElementGuid>ebdb72ea-166f-47d9-ab29-7586402dcb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Widget containing checkbox for hCaptcha security challenge</value>
      <webElementGuid>b19c0a5a-a647-4753-844d-168bd5e66d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hcaptcha-widget-id</name>
      <type>Main</type>
      <value>09txwjy6j9lb</value>
      <webElementGuid>357109f4-1fec-4f74-878e-2f0ba185ba14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h-captcha&quot;)/iframe[1]</value>
      <webElementGuid>bbcb10ce-8c22-4c8f-9beb-41f7d22eeba4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='h-captcha']/iframe</value>
      <webElementGuid>c93da10f-7edc-4665-9c23-33f34e94756b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e355f9b6-c93d-438a-aea2-90278ba50a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://newassets.hcaptcha.com/captcha/v1/6416769/static/hcaptcha.html#frame=checkbox&amp;id=09txwjy6j9lb&amp;host=ltopcorner.myshopify.com&amp;sentry=true&amp;reportapi=https%3A%2F%2Faccounts.hcaptcha.com&amp;recaptchacompat=off&amp;custom=false&amp;hl=en&amp;tplinks=on&amp;pstissuer=https%3A%2F%2Fpst-issuer.hcaptcha.com&amp;sitekey=854574d3-241c-4eeb-95cc-896eb71d0349&amp;theme=light&amp;origin=https%3A%2F%2Fltopcorner.myshopify.com' and @title = 'Widget containing checkbox for hCaptcha security challenge']</value>
      <webElementGuid>e722ccc1-aa73-42a1-bf95-a8d5df899c51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
