<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d61d8ce6-fe9c-4496-8b0d-5b7675296790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Shopify&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Shopify']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Shopify&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c44624b7-8e82-42bb-98a2-96cbcff1a82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Shopify</value>
      <webElementGuid>6c62e343-6a3d-43df-86b5-e826a003ee63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shopify-assets.shopifycdn.com/accounts/production/theme_configuration/logo/oauth_provider/merchant/logo.svg?v=1631025778</value>
      <webElementGuid>7e753900-704d-414e-a286-20bbd164a21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fresh-html&quot;]/body[@class=&quot;page-layout fresh-ui&quot;]/div[2]/div[@class=&quot;ui-app-frame&quot;]/header[@class=&quot;ui-app-frame__header&quot;]/div[@class=&quot;ui-top-bar&quot;]/div[@class=&quot;ui-top-bar__list&quot;]/div[@class=&quot;ui-top-bar__item ui-top-bar__item--fill&quot;]/div[@class=&quot;ui-navbar__logo&quot;]/a[1]/img[1]</value>
      <webElementGuid>388563b0-83e0-437a-83ec-01503e07f2ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Shopify']</value>
      <webElementGuid>c94c2194-453d-4576-ac3b-d2ed14da86b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a08f0a78-da25-406b-911a-1581786a9a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Shopify' and @src = 'https://shopify-assets.shopifycdn.com/accounts/production/theme_configuration/logo/oauth_provider/merchant/logo.svg?v=1631025778']</value>
      <webElementGuid>695443de-7961-474f-9f39-f10715fb06c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
