<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__filter.v.price.lte</name>
   <tag></tag>
   <elementGuidId>f665ab46-ee0e-439b-9029-1393f848215d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Filter-Price-LTE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Filter-Price-LTE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;To&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f709c7e6-d1ef-4eef-87db-073414cfd1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field__input</value>
      <webElementGuid>afba0bb3-5ea2-4923-93ca-1eb8a2756e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter.v.price.lte</value>
      <webElementGuid>fb4250a6-fff0-447c-9f02-10b74950f135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Filter-Price-LTE</value>
      <webElementGuid>b40b334c-4e20-4915-a891-d483bdb11800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>807f86da-af3c-48d5-ba6d-528dd4a7efdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>4b3d1559-f84d-405c-8a82-95b58047b558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>2,099.00</value>
      <webElementGuid>e04635f6-fbc5-4e3e-af8a-7390e8b9da7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern</name>
      <type>Main</type>
      <value>\d| |,|\.</value>
      <webElementGuid>e11e6450-7469-409a-b5eb-d71d3fc8d88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>98fb376f-91d4-4640-a5d8-241d7630a203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>2,099.00</value>
      <webElementGuid>52bd0bc3-e4c8-41e3-bed3-294ff8fdb128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Filter-Price-LTE&quot;)</value>
      <webElementGuid>5f1a07a8-7253-49c1-9fa8-e1f369e0d965</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Filter-Price-LTE']</value>
      <webElementGuid>fa5339b1-63fd-444f-997c-8620f3f9148b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Facet-2-template--17877713813672__product-grid']/price-range/div[2]/input</value>
      <webElementGuid>1e10e48d-af6d-4714-9ae7-db1518f02239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ad37caf0-2d8b-45a7-ae94-e3b7efb3698d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'filter.v.price.lte' and @id = 'Filter-Price-LTE' and @type = 'text' and @placeholder = '2,099.00']</value>
      <webElementGuid>faebe53b-f339-4f0d-83fc-491dabf171bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
