<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADIDAS  CLASSIC BACKPACK</name>
   <tag></tag>
   <elementGuidId>a554801a-2af8-4ec4-b48d-51774f5c790b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardLink-template--18610480578783__product-grid-8834482045151</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CardLink-template--18610480578783__product-grid-8834482045151']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ADIDAS | CLASSIC BACKPACK Sale&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c19cb54f-820e-4155-a327-03bb37ca89b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/adidas-classic-backpack</value>
      <webElementGuid>9439c6f5-f458-4826-8a71-d854c47d65b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834482045151</value>
      <webElementGuid>75193905-22e6-4d27-b516-1a7e7b2ec860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>4d37c6d0-b740-4cf4-aa66-cd0dcbab7181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834482045151 Badge-template--18610480578783__product-grid-8834482045151</value>
      <webElementGuid>ce1de1bc-f0c0-4ac5-b9fc-ea79fc95a5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              ADIDAS | CLASSIC BACKPACK
            </value>
      <webElementGuid>209b96d2-c5d3-4618-b914-e797b257067f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink-template--18610480578783__product-grid-8834482045151&quot;)</value>
      <webElementGuid>abc7c397-f916-4fac-9b3c-a814aa4266ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink-template--18610480578783__product-grid-8834482045151']</value>
      <webElementGuid>beb7ed08-84c0-402e-9226-e13688abbb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title-template--18610480578783__product-grid-8834482045151']/a</value>
      <webElementGuid>bab5c57f-8a30-4511-907c-47d71580106e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ADIDAS | CLASSIC BACKPACK')])[2]</value>
      <webElementGuid>6a4af593-e7a6-4e40-9076-cfc132d411fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale'])[1]/following::a[1]</value>
      <webElementGuid>e782f09b-bcd2-4d0b-90c3-0939f5e3668d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADIDAS | CLASSIC BACKPACK'])[1]/following::a[1]</value>
      <webElementGuid>10b53c91-b186-4f6a-adda-25a67c8fe824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[1]/preceding::a[1]</value>
      <webElementGuid>4922160b-e833-4329-947f-cb00cf66e071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 56.00'])[1]/preceding::a[1]</value>
      <webElementGuid>5a88d469-3bd5-4cb0-920a-3d57b48606ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/adidas-classic-backpack')])[2]</value>
      <webElementGuid>6f722d6c-4b40-4cc5-a0c3-b57a807fc6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3/a</value>
      <webElementGuid>09192539-00bd-4da3-9d48-c7a201dd6412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/adidas-classic-backpack' and @id = 'CardLink-template--18610480578783__product-grid-8834482045151' and (text() = '
              ADIDAS | CLASSIC BACKPACK
            ' or . = '
              ADIDAS | CLASSIC BACKPACK
            ')]</value>
      <webElementGuid>b982e81b-fd1d-40e2-870c-fb63c55644e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
