<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uncover your wardrobe essentials_Onl_54202d (1)</name>
   <tag></tag>
   <elementGuidId>c1ef40e5-b3cc-4ab7-9cac-d525f9289cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Online-Store-UI-NavItem__PrimaryAction_eiqvh.Online-Store-UI-NavItem--hovered_fsbep</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[52]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Buttons&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>43d260f0-b18c-4ec6-a737-bd98f00bbf02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>414b3a26-2442-40c7-8ea7-bf2c0d32bb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Online-Store-UI-NavItem__PrimaryAction_eiqvh Online-Store-UI-NavItem--hovered_fsbep</value>
      <webElementGuid>b008c5c0-84f1-43d7-84f8-08f82b597ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>template--18610480611551__image_banner__button-label</value>
      <webElementGuid>548b60e8-5a34-495d-805d-a7f77e0641c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;template--18610480611551__image_banner__button&quot;)/div[@class=&quot;Online-Store-UI-NavItem__Interior_1tclk Online-Store-UI-NavItem--fleeting_nly7t&quot;]/button[@class=&quot;Online-Store-UI-NavItem__PrimaryAction_eiqvh Online-Store-UI-NavItem--hovered_fsbep&quot;]</value>
      <webElementGuid>14c66c13-e878-468f-8d62-7455b0d2fab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Banner/Page_Threads  Customize Dawn  Shopify/iframe_Skip to content_be8a246c-a367-4c3c-a_5a2f4f</value>
      <webElementGuid>7a5452c8-2184-47ff-807a-5f7e352900a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[52]</value>
      <webElementGuid>141461b3-ca76-4b49-8396-9807d58f15c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='template--18610480611551__image_banner__button']/div/button</value>
      <webElementGuid>c16bb42b-c1f3-44f1-81db-89a431b22118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ol/li[2]/div/button</value>
      <webElementGuid>47d3778b-d940-4e4d-8d16-e1f32a601075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>0d0ad023-7088-413a-bdae-276664c61026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
