<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uncover your wardrobe essentials_Onl_54202d</name>
   <tag></tag>
   <elementGuidId>39043f25-b1d0-46ca-8a85-1dd821daa05f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Online-Store-UI-NavItem__PrimaryAction_eiqvh.Online-Store-UI-NavItem--hovered_fsbep</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[52]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Buttons&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3862cac9-2470-4756-9a2f-c7664d5049e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfffcee6-5ac2-4e62-892e-bfc37de9b973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Online-Store-UI-NavItem__PrimaryAction_eiqvh Online-Store-UI-NavItem--hovered_fsbep</value>
      <webElementGuid>48858b63-37a4-4918-a3c6-8304c660cf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>template--18610480611551__image_banner__button-label</value>
      <webElementGuid>cdd280a3-6d28-4742-8cdb-1ecd7abcf509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;template--18610480611551__image_banner__button&quot;)/div[@class=&quot;Online-Store-UI-NavItem__Interior_1tclk Online-Store-UI-NavItem--fleeting_nly7t&quot;]/button[@class=&quot;Online-Store-UI-NavItem__PrimaryAction_eiqvh Online-Store-UI-NavItem--hovered_fsbep&quot;]</value>
      <webElementGuid>c89f2e2b-91e6-4411-9d78-b5b3436660dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Banner/Page_Threads  Customize Dawn  Shopify/iframe_Skip to content_21babb25-8e7e-4493-9_120058</value>
      <webElementGuid>172f5857-f114-4423-9652-e97e84cca382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[52]</value>
      <webElementGuid>2b890929-f911-44da-abeb-f96d350c39c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='template--18610480611551__image_banner__button']/div/button</value>
      <webElementGuid>cf61edbd-c00f-4b62-92b8-6d6f4e236a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ol/li[2]/div/button</value>
      <webElementGuid>3d6c930d-426b-429e-80ee-21a2f0b708c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>718e63e3-e2fe-45b5-b182-3ace893948ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
