<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uncover your wardrobe essentials_Onl_54202d (2)</name>
   <tag></tag>
   <elementGuidId>f2582986-79f0-42b4-b7c3-c3c596f4121b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Online-Store-UI-NavItem__PrimaryAction_eiqvh.Online-Store-UI-NavItem--hovered_fsbep</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[52]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Buttons&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>afbd4457-867e-408f-8ce8-aea924d3ba06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>122991ad-c444-4c00-8661-3ce0362c6d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Online-Store-UI-NavItem__PrimaryAction_eiqvh Online-Store-UI-NavItem--hovered_fsbep</value>
      <webElementGuid>b5dd61cd-7d80-4373-8a2e-605cd107e75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>template--18610480611551__image_banner__button-label</value>
      <webElementGuid>49477b2b-a290-4ca2-8398-19b97dfb57fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;template--18610480611551__image_banner__button&quot;)/div[@class=&quot;Online-Store-UI-NavItem__Interior_1tclk Online-Store-UI-NavItem--fleeting_nly7t&quot;]/button[@class=&quot;Online-Store-UI-NavItem__PrimaryAction_eiqvh Online-Store-UI-NavItem--hovered_fsbep&quot;]</value>
      <webElementGuid>a9112eb6-90f1-47eb-a19b-6d21137c6c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Banner/Page_Threads  Customize Dawn  Shopify/iframe_Skip to content_fe56d741-3ec3-491d-b_5f461d</value>
      <webElementGuid>00fdd0a9-7f16-4b45-b5c4-4f248097c898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[52]</value>
      <webElementGuid>2c92228b-64aa-43fb-be28-5b3b297d8bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='template--18610480611551__image_banner__button']/div/button</value>
      <webElementGuid>3aacb3fa-d755-4ebf-9cdd-a1cedc5ccdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ol/li[2]/div/button</value>
      <webElementGuid>42ba415b-bf46-4cda-8032-31c0332be212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>6a7b0582-e228-4081-9110-c31b3840996c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
