<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Remove block_1</name>
   <tag></tag>
   <elementGuidId>c8cd41a6-564d-4bbe-b087-24489931d202</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#storefront-iframe-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='storefront-iframe-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;\31 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>987e388f-82be-41d9-a1cb-107fdc4ea32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>storefront-iframe-0</value>
      <webElementGuid>081c69f7-6066-4f5f-ab4d-0411f9e76f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3053bccc-5365-437b-bbc6-19e6bec54d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://threads0.myshopify.com/?key=009b0790536e60bdae926bdcae2d62230b4b76403b4fe538063902d915b21d96&amp;_bt=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaHQwYUhKbFlXUnpNQzV0ZVhOb2IzQnBabmt1WTI5dEJqb0dSVlE9IiwiZXhwIjoiMjAyNC0xMS0wNFQwNzo1MjozMy4xOTVaIiwicHVyIjoicGVybWFuZW50X3Bhc3N3b3JkX2J5cGFzcyJ9fQ%3D%3D--aa11b5eca87f10d8ae43213a59a1d5a3d99005fe&amp;oseid=GSRKcGQ3HMDaXAFEJqG28LrM</value>
      <webElementGuid>919fb118-5686-4176-951c-f616c9eb25d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Online store preview</value>
      <webElementGuid>61e77ab1-2ca9-4864-9f86-dcee5fe3ba0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ZCKBY pFV6j</value>
      <webElementGuid>e4e96590-0e7d-42e6-aa3e-985b9e9d44f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>910116a1-16dd-4baf-b922-fd2c83b32f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-same-origin allow-forms allow-popups allow-scripts allow-modals allow-storage-access-by-user-activation</value>
      <webElementGuid>2acd2d1f-9af6-4ca1-aaa0-c0d7823239d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storefront-iframe-0&quot;)</value>
      <webElementGuid>4cd88e8b-17b8-412f-a973-0e8acb1365e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Banner/Page_Threads  Customize Dawn  Shopify/iframe_Skip to content_a99f666a-be2e-4590-8_37dbfe</value>
      <webElementGuid>26a06989-edac-4ac7-af70-50cc6eaf8a4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='storefront-iframe-0']</value>
      <webElementGuid>02029b82-6e92-401d-ae3d-956390fd336b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/main/div/div/div[2]/div/div/iframe</value>
      <webElementGuid>dc8b7d32-ec73-4dd5-9704-1aae31798d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div[2]/div/div/iframe</value>
      <webElementGuid>8fc8bc4e-da86-4ab6-8d2e-aa443a4fd6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'storefront-iframe-0' and @name = '1' and @src = 'https://threads0.myshopify.com/?key=009b0790536e60bdae926bdcae2d62230b4b76403b4fe538063902d915b21d96&amp;_bt=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaHQwYUhKbFlXUnpNQzV0ZVhOb2IzQnBabmt1WTI5dEJqb0dSVlE9IiwiZXhwIjoiMjAyNC0xMS0wNFQwNzo1MjozMy4xOTVaIiwicHVyIjoicGVybWFuZW50X3Bhc3N3b3JkX2J5cGFzcyJ9fQ%3D%3D--aa11b5eca87f10d8ae43213a59a1d5a3d99005fe&amp;oseid=GSRKcGQ3HMDaXAFEJqG28LrM' and @title = 'Online store preview']</value>
      <webElementGuid>98aef30f-29f0-4168-a1e0-55b8f366d24e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
