<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First button link_UrlSetting1 (5)</name>
   <tag></tag>
   <elementGuidId>dc42b2ac-11b0-4378-b2df-cf38add46743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UrlSetting1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UrlSetting1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First button link&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5993e793-9ca6-48da-b500-0d946ac4fa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UrlSetting1</value>
      <webElementGuid>6e75c5dc-bf1a-4951-88e5-25869c3f78ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Paste a link or search</value>
      <webElementGuid>ead7f4fb-89b0-4c4d-aed5-bdfcc5e38722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5fe99c03-d2dc-4e57-9632-2ecb7fd73658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-TextField__Input Polaris-TextField__Input--hasClearButton Polaris-TextField--compact</value>
      <webElementGuid>295789a4-94da-4816-86af-0edb2bc9ae18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce030866-7499-484b-9edf-c3c38577554b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>UrlSetting1Label UrlSetting1-Prefix</value>
      <webElementGuid>ffc4131a-5701-4852-bcd4-f60bbe65911a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5251cd11-09c0-445f-8e36-0f3f6b7cb884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9dcfef11-d164-4d26-af2f-22e6573bf545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b2e6fc5f-8fbb-4688-992a-3d6318119e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form-type</name>
      <type>Main</type>
      <value>other</value>
      <webElementGuid>06c7c884-b30b-4587-aff3-0418b8046fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ASICS TIGER</value>
      <webElementGuid>9b1d0f2e-2b4f-4155-a416-12571c45d837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dde967ae-0c7b-470a-9d6e-5e56edf9b7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>fcb04279-1a0a-43df-a95c-1f8f49966432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UrlSetting1&quot;)</value>
      <webElementGuid>99fc62bd-194b-41b1-b91b-67f771fd7652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Banner/Page_Threads  Customize Dawn  Shopify/iframe_Skip to content_5698d275-b1aa-46e9-b_f1a7ce</value>
      <webElementGuid>3b25741a-bd41-4f6e-a46f-1d66bf57a0f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UrlSetting1']</value>
      <webElementGuid>366a9bea-7627-4e6a-a159-e9f7bb84f093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/aside/div/div[4]/div/div/section[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>2553d82c-6697-4b07-8725-253312a24b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>e4b925eb-6ef3-40dc-ad59-44d782b2cffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UrlSetting1' and @placeholder = 'Paste a link or search' and @type = 'text']</value>
      <webElementGuid>c0cf059e-1934-4dbc-a2b3-b07bf6a6d811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
