<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First button label_TextSetting-Label1</name>
   <tag></tag>
   <elementGuidId>02f30521-20b3-45ec-9d5d-5f81d567277c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TextSetting-Label1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TextSetting-Label1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First button label&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0058db68-1987-496f-9e13-d11024d93d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TextSetting-Label1</value>
      <webElementGuid>3578d230-4fd5-4a38-86f1-393856d79ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c5758391-2a56-4e54-b2d5-a1a7fe1514c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-TextField__Input Polaris-TextField--compact</value>
      <webElementGuid>0bbe7438-4ff7-478b-b102-cd4e71469499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ffb3408d-fd4f-46c9-94c6-b696b5cd93ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>TextSetting-Label1Label</value>
      <webElementGuid>e982b312-7078-429b-a706-59455d6d7386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>889f5b01-a9b5-425f-bef8-b976edc48521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48e9e520-5459-4e39-9c88-416505e0553b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b43dd8e-da6f-4b46-9de1-bcd3429d3a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form-type</name>
      <type>Main</type>
      <value>other</value>
      <webElementGuid>a82bfb0c-8cef-46cf-8290-4ac080f99362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Explore Threads</value>
      <webElementGuid>317e4ee4-ebcd-4dbb-b7d0-795193b5eb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TextSetting-Label1&quot;)</value>
      <webElementGuid>4d404684-d844-4e56-9772-ab05b8509210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Banner/Page_Threads  Customize Dawn  Shopify/iframe_Skip to content_a99f666a-be2e-4590-8_37dbfe</value>
      <webElementGuid>453989d0-3f75-4c67-bd7e-670b2fc10088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TextSetting-Label1']</value>
      <webElementGuid>c37a2e7f-07e9-42b9-af3c-4a0d3dd94854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/aside/div/div[4]/div/div/section[2]/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>8de82a01-611a-43cb-a37e-a4f2d3794c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>7e951ba1-7b79-44e3-9f71-900b5adbb3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TextSetting-Label1' and @type = 'text']</value>
      <webElementGuid>283458b0-22e9-4bb2-aae7-edea56d121b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
