<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First button link_UrlSetting1 (4)</name>
   <tag></tag>
   <elementGuidId>af74a280-b15f-4863-9461-ef13d6640c5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UrlSetting1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UrlSetting1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First button link&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30e6444a-f509-4ce4-9f3b-6e8c9b17e073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UrlSetting1</value>
      <webElementGuid>8bc72b9f-6557-4e86-aa8c-98a7d295a92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Paste a link or search</value>
      <webElementGuid>3f580277-1646-4845-9295-d602e0a61926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>796edd66-1b36-4014-978b-8c13dd4630f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-TextField__Input Polaris-TextField__Input--hasClearButton Polaris-TextField--compact</value>
      <webElementGuid>2ac4d3d6-19b7-45b7-95a7-3b77526869c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc05c064-ff30-40d3-b8c3-700aa544a5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>UrlSetting1Label UrlSetting1-Prefix</value>
      <webElementGuid>cd0a1747-ebba-4048-8cac-0f2cc8d86a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c1c755e-b286-4847-a5fd-f6f4ce5163cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2891a8b7-6ccf-43b8-b583-c039ba3af98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6056088e-5c9a-43ad-8486-87a4fad86862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form-type</name>
      <type>Main</type>
      <value>other</value>
      <webElementGuid>6c51961c-6b53-480b-9f75-ef92bfc65281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>All Products</value>
      <webElementGuid>1c51a7fe-e794-4b2e-9811-2257c3c08c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1fceebe7-6ff2-4b5e-a66a-b334627ab1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>16fad1d8-a1a0-4747-9600-286dce770699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UrlSetting1&quot;)</value>
      <webElementGuid>4de86514-88e3-4e34-a763-24694e89415b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Banner/Page_Threads  Customize Dawn  Shopify/iframe_Skip to content_fe56d741-3ec3-491d-b_5f461d</value>
      <webElementGuid>a4912dbc-6b38-4410-b4ea-7857e0bd7abe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UrlSetting1']</value>
      <webElementGuid>d91782b8-f5f7-45b6-9016-655bc4f0a278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/aside/div/div[4]/div/div/section[2]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>759c1edc-5cb4-4d0a-8f1f-ff51612b6c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>3268c36e-ead8-47b9-8785-70aa681fe693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UrlSetting1' and @placeholder = 'Paste a link or search' and @type = 'text']</value>
      <webElementGuid>b28f414d-2c5b-4954-bf7a-4323761c8925</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
