<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__filter.v.price.lte</name>
   <tag></tag>
   <elementGuidId>06dd66b9-72f7-4eec-8f23-420b5558beae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Filter-Price-LTE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Filter-Price-LTE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;To&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7f8be2f-2622-4a46-828e-87a50e03b7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field__input</value>
      <webElementGuid>181e9f4f-5506-4228-bc88-384dcdc5dace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter.v.price.lte</value>
      <webElementGuid>8df8ce52-73f7-4313-9a21-17eeeb8e1083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Filter-Price-LTE</value>
      <webElementGuid>703f1c23-6e3f-462c-95a8-606e03f42396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b985400-2e69-4e7b-8876-4377f30401b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>f4af4bec-d10b-4b92-98ff-e9981a3bf98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>299.95</value>
      <webElementGuid>857efcd1-bbca-4935-992d-f8796d82c495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern</name>
      <type>Main</type>
      <value>\d| |,|\.</value>
      <webElementGuid>7b800f53-069e-44d2-800b-551cfa048ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>199</value>
      <webElementGuid>0d5a71a5-fd14-4a0e-9a28-2a7d2693d9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-max</name>
      <type>Main</type>
      <value>299.95</value>
      <webElementGuid>857ced04-1843-48a5-a06c-8bb2dfc71e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Filter-Price-LTE&quot;)</value>
      <webElementGuid>af4102e2-2c58-4787-a76e-7de57c777fc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Filter-Price-LTE']</value>
      <webElementGuid>40fd440b-44f6-441e-9c95-71b16ba114d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Facet-2-template--18610480578783__product-grid']/price-range/div[2]/input</value>
      <webElementGuid>9b6eba3a-2a4d-4628-bd8c-064ad6f100f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>90e50604-5a0f-49cf-828d-fa1325a46357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'filter.v.price.lte' and @id = 'Filter-Price-LTE' and @type = 'text' and @placeholder = '299.95']</value>
      <webElementGuid>0a08bf98-b58e-4969-9e3e-f3e35b8cc3cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
