<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Payment</name>
   <tag></tag>
   <elementGuidId>214ad893-897a-4821-92db-542af2ccea7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.n8k95w1.n8k95w0._1fragemlj.n8k95w2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='Form1']/div/section/div/div/div/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Payment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>31fc09dd-9053-419a-9947-d2a000d4ee2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>n8k95w1 n8k95w0 _1fragemlj n8k95w2</value>
      <webElementGuid>d5690447-12e5-4e90-a9e0-8a0ec45558a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment</value>
      <webElementGuid>f035ea35-5805-4a73-a525-7b7085b78cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form1&quot;)/div[@class=&quot;km09ry1 _1fragemlj&quot;]/section[@class=&quot;_197l2ofi _197l2ofg _1fragemna _197l2ofp _197l2ofk _1fragemn6 _1fragemsy _1fragem1y _1fragemf0 _1fragemg0 _1fragemh3 _1fragemht _1fragemd7 _1frageme7 _1fragemiw _1fragemjm _1fragemlj&quot;]/div[1]/div[1]/div[@class=&quot;_1fragem1y _1fragemlj&quot;]/div[@class=&quot;_1ip0g651 _1ip0g650 _1fragemlj _1fragem3w _1fragem5p _1fragem2s&quot;]/div[@class=&quot;_1ip0g651 _1ip0g650 _1fragemlj _1fragem3c _1fragem55 _1fragem2s&quot;]/h2[@class=&quot;n8k95w1 n8k95w0 _1fragemlj n8k95w2&quot;]</value>
      <webElementGuid>a3dbb58b-a36b-4562-b7eb-71f164aa1b0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form1']/div/section/div/div/div/div/div/h2</value>
      <webElementGuid>a03c60ee-9272-498e-b45d-b08f7edb0294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email me with news and offers'])[1]/following::h2[1]</value>
      <webElementGuid>f570fe50-e087-4935-9f1c-85f9b05f3117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹10.00'])[1]/following::h2[1]</value>
      <webElementGuid>96b05afe-dc71-4675-bdf5-d743730cce62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit card'])[1]/preceding::h2[1]</value>
      <webElementGuid>bef5e6ce-70dc-403c-8e60-55e7a6d128ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card number'])[1]/preceding::h2[2]</value>
      <webElementGuid>d2fa5c85-5aab-4c3e-b666-b3dcb66a7a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment']/parent::*</value>
      <webElementGuid>c57fa9cb-9ca3-4d2d-ba21-bf8914c9b93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div/div/div/h2</value>
      <webElementGuid>216f14ea-62a8-4fd2-993f-1337dfa16ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Payment' or . = 'Payment')]</value>
      <webElementGuid>deb4ca91-7bc1-482a-95ad-6c1a5b87c72f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
