<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>06ab4e7c-6af0-4513-96de-03750e4dae00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button._1m2hr9ge._1m2hr9gd._1fragemsq._1fragemlj._1fragemnk._1fragem2i._1fragems4._1fragemsg._1fragemsl._1fragemsa._1m2hr9g1h._1m2hr9g1d._1fragemne._1m2hr9g16._1m2hr9g13._1fragemop._1fragemon._1fragemor._1fragemol._1fragempl._1fragemph._1fragempp._1fragempd._1fragemb4._1fragemaf._1fragembt._1fragem9q._1fragemsa._1m2hr9g1q._1m2hr9g1o._1m2hr9g10._1m2hr9gx._1m2hr9g1b._1m2hr9g19._1fragems5._1m2hr9g25</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Apply Discount Code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7cb3e64-2e8f-45b4-8b95-9e073781a3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0d95ff5c-501a-4e2c-86ab-dc6c8fbdedb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Apply Discount Code</value>
      <webElementGuid>4aa085fc-ad18-4858-a707-12f21fa85bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1m2hr9ge _1m2hr9gd _1fragemsq _1fragemlj _1fragemnk _1fragem2i _1fragems4 _1fragemsg _1fragemsl _1fragemsa _1m2hr9g1h _1m2hr9g1d _1fragemne _1m2hr9g16 _1m2hr9g13 _1fragemop _1fragemon _1fragemor _1fragemol _1fragempl _1fragemph _1fragempp _1fragempd _1fragemb4 _1fragemaf _1fragembt _1fragem9q _1fragemsa _1m2hr9g1q _1m2hr9g1o _1m2hr9g10 _1m2hr9gx _1m2hr9g1b _1m2hr9g19 _1fragems5 _1m2hr9g25</value>
      <webElementGuid>c19d037b-c2cc-41d5-b1ec-f7633bf96feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>e99bd349-ae34-4aff-b6be-82eb5ba5fa60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form0&quot;)/div[@class=&quot;km09ry1 _1fragemlj&quot;]/div[@class=&quot;_1mrl40q0 _1fragemlj _1fragem2s _1fragem3c _1fragem5p _1fragemm3 _16s97g7f _16s97g7p _16s97g71j _16s97g71t&quot;]/button[@class=&quot;_1m2hr9ge _1m2hr9gd _1fragemsq _1fragemlj _1fragemnk _1fragem2i _1fragems4 _1fragemsg _1fragemsl _1fragemsa _1m2hr9g1h _1m2hr9g1d _1fragemne _1m2hr9g16 _1m2hr9g13 _1fragemop _1fragemon _1fragemor _1fragemol _1fragempl _1fragemph _1fragempp _1fragempd _1fragemb4 _1fragemaf _1fragembt _1fragem9q _1fragemsa _1m2hr9g1q _1m2hr9g1o _1m2hr9g10 _1m2hr9gx _1m2hr9g1b _1m2hr9g19 _1fragems5 _1m2hr9g25&quot;]</value>
      <webElementGuid>a40549d5-66aa-4aba-a824-231f2c3c7848</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>11343bfa-0e94-4e4e-b945-92f92f1c21ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form0']/div/div/button</value>
      <webElementGuid>9469ee87-f354-4350-b372-ac6871011a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discount code'])[1]/following::button[1]</value>
      <webElementGuid>14c2c80a-6006-4e0d-b925-edd426517ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹220.00'])[1]/following::button[1]</value>
      <webElementGuid>381c3881-8986-4b5a-a904-ddc7eabbdbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost summary'])[1]/preceding::button[2]</value>
      <webElementGuid>a03334e3-a287-4f9e-9bc8-1b2d4c7133a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/button</value>
      <webElementGuid>d07f6ab8-7717-4136-88d5-44f6e545b340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>a414a2aa-bcf0-42d4-bf8a-c1929003f5a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
