<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Expiration date (MM  YY)_card-fields_b17af0</name>
   <tag></tag>
   <elementGuidId>1a40d4ff-5002-4c4a-aa66-492ad1f0fab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-expiry-zpejuh4yr7f00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-expiry-zpejuh4yr7f00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-expiry-zpejuh4yr7f00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>047fc8d5-bf2a-48af-a2f9-db3b1c24c7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>73c03d75-3f69-4438-89a3-7b758d07bc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a5df6160-c2a1-4466-b07d-d3a84eef95bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-expiry-zpejuh4yr7f00000</value>
      <webElementGuid>565ef89e-5c5b-482a-98e0-9143aee3c0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-expiry-zpejuh4yr7f00000</value>
      <webElementGuid>e31ab114-b1b0-46e3-aa49-54dff7bd7c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>116284fd-7ee7-4b59-9c95-51efd0de2994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/expiry?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>6f4be6ec-6d76-4784-a82d-1ed3f75e7038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Expiration date (MM / YY)</value>
      <webElementGuid>fa283873-fbd5-4f5a-bf80-e691968655d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-expiry-zpejuh4yr7f00000&quot;)</value>
      <webElementGuid>572b1245-1af5-4bf8-902f-3e216a6302cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-expiry-zpejuh4yr7f00000']</value>
      <webElementGuid>c64682ee-0f74-456e-a5cd-b6da9bfab869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expiry']/iframe</value>
      <webElementGuid>222ff2c6-3964-493d-87e7-7d6f0bc96d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/iframe</value>
      <webElementGuid>cc513436-744b-40f2-97cc-6bff50408556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-expiry-zpejuh4yr7f00000' and @name = 'card-fields-expiry-zpejuh4yr7f00000' and @src = 'https://checkout.pci.shopifyinc.com/expiry?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Expiration date (MM / YY)']</value>
      <webElementGuid>060f339e-285f-4966-a678-fb1212cd6fe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
