<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Expiration date (MM  YY)_card-fields_715201</name>
   <tag></tag>
   <elementGuidId>2b7b2311-f0af-44a0-aa73-858a95381509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-expiry-du22z9h93q000000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-expiry-du22z9h93q000000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-expiry-du22z9h93q000000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3d0f8baf-9841-4d57-a339-dfb7caf086f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>0b645fcf-2473-4547-8759-4093972f744e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ee0af7f7-22a4-4d86-802a-b55e651653e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-expiry-du22z9h93q000000</value>
      <webElementGuid>b9d82091-c8d2-48f7-aae9-f4d9599954c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-expiry-du22z9h93q000000</value>
      <webElementGuid>81776c52-5f31-473b-99a3-63adc4095a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>dfe0c8eb-b51f-4f96-8b90-cec053c0c7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/expiry?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>b4602714-62b0-454d-b32a-bfe2184eedef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Expiration date (MM / YY)</value>
      <webElementGuid>0f5b1f62-2bb8-44e0-83a9-cf268eb6e7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-expiry-du22z9h93q000000&quot;)</value>
      <webElementGuid>81b1c48f-fc54-4e1b-9e2b-9626ef9bb986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-expiry-du22z9h93q000000']</value>
      <webElementGuid>856e203b-1757-43c3-b19c-6bafce3ff02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expiry']/iframe</value>
      <webElementGuid>08220a4b-40ab-4f04-8935-e3642e3bfd15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/iframe</value>
      <webElementGuid>b67a5bdb-2529-4f36-bfb5-09770cadc524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-expiry-du22z9h93q000000' and @name = 'card-fields-expiry-du22z9h93q000000' and @src = 'https://checkout.pci.shopifyinc.com/expiry?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Expiration date (MM / YY)']</value>
      <webElementGuid>5518c8ce-7165-47c0-9eb1-2663df6f761c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
