<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card number_card-fields-number-xdjuu_727354</name>
   <tag></tag>
   <elementGuidId>126d8de6-8334-4599-ad6c-1b8aea238e35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-number-xdjuuwcz27000000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-number-xdjuuwcz27000000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-number-xdjuuwcz27000000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5a5a7b6b-6f72-4a75-831c-2083ebc55c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>0ccac114-2697-4636-9268-27284099147b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d3743a70-59ff-4d4f-87c0-f28de33f2633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-number-xdjuuwcz27000000</value>
      <webElementGuid>32644acf-45b4-401c-beef-e3030552649f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-number-xdjuuwcz27000000</value>
      <webElementGuid>6a4a819c-bda7-4840-aad7-9bd55c136034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>55916b4b-8600-4ab5-b6bc-8443e0f28470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/number?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>dfdbd2f1-8094-4d98-9c3b-7ed09f0f3366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Card number</value>
      <webElementGuid>79b65409-e060-4a37-81b4-7426263bca4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-number-xdjuuwcz27000000&quot;)</value>
      <webElementGuid>3d6b33f9-400e-4819-90e0-c74e8e64b4c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-number-xdjuuwcz27000000']</value>
      <webElementGuid>26bed6f7-6079-4e8b-bf63-5ad244c9f0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='number']/iframe</value>
      <webElementGuid>a2927b2b-7967-4c7d-9f14-4e1fad6f8486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8033f1c3-ce78-4e74-a9fa-06a304502602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-number-xdjuuwcz27000000' and @name = 'card-fields-number-xdjuuwcz27000000' and @src = 'https://checkout.pci.shopifyinc.com/number?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Card number']</value>
      <webElementGuid>a67cc666-d0e7-46f8-85b7-4a4f96c6028b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
