<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Name on card_card-fields-name-p7oyqf_89c151</name>
   <tag></tag>
   <elementGuidId>6919a98a-7b4b-42f5-96d0-81849e97414c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-name-p7oyqfjv79n00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-name-p7oyqfjv79n00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-name-p7oyqfjv79n00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b10e4792-37ad-4e5e-a910-d9032dd2a180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>97011ec7-b3f7-4c1f-8e6c-ae9284eaa47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>79a2c77e-4d2b-4f1e-ac42-566a123041f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-name-p7oyqfjv79n00000</value>
      <webElementGuid>a1205d06-b88a-46ce-9bfc-946bafae468e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-name-p7oyqfjv79n00000</value>
      <webElementGuid>4dbfff0e-1610-438a-9d4a-752681dd4696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>45870f30-7a32-41b8-a560-22c77b6303a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/name?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>34983f92-2732-4418-8bf3-404466883392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Name on card</value>
      <webElementGuid>18d71614-89c3-49df-a177-ba86cec8fcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-name-p7oyqfjv79n00000&quot;)</value>
      <webElementGuid>af34b969-bcbc-4375-a8f8-d05182588ad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-name-p7oyqfjv79n00000']</value>
      <webElementGuid>a01b1ec7-6329-441a-a3f3-739733695688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name']/iframe</value>
      <webElementGuid>909870b7-3d31-4101-972d-834d1e1ea181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/iframe</value>
      <webElementGuid>7d726d87-28de-4c35-bda2-5301e31c92ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-name-p7oyqfjv79n00000' and @name = 'card-fields-name-p7oyqfjv79n00000' and @src = 'https://checkout.pci.shopifyinc.com/name?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Name on card']</value>
      <webElementGuid>f24cab52-fd9b-40f2-9cce-035aa62e2454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
