<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Name on card_card-fields-name-h8mxeq_b22138</name>
   <tag></tag>
   <elementGuidId>8311008c-15ec-47a2-a85f-2b599a30364b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-name-h8mxeqginvn00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-name-h8mxeqginvn00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-name-h8mxeqginvn00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a38c74bb-5bee-4522-a4f9-d22fc9f9a203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>8c0fa542-ebe7-478f-bc5a-bcadf58d40ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>65f497c1-e0d7-428f-a64d-f4a422b3245b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-name-h8mxeqginvn00000</value>
      <webElementGuid>b7e62c89-b01e-447a-bb07-c4166f58de42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-name-h8mxeqginvn00000</value>
      <webElementGuid>b557b196-1b65-49dc-80cc-2dfef3d7e52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>65ce01ad-091d-4b72-9f9c-e570a3510f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/name?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>53209833-3949-4479-89ff-3c6936f6444b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Name on card</value>
      <webElementGuid>03aceeb7-dfe2-4218-bec9-e95f25838e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-name-h8mxeqginvn00000&quot;)</value>
      <webElementGuid>6c67a7bf-6005-4a1f-9381-054a73d3c349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-name-h8mxeqginvn00000']</value>
      <webElementGuid>e098dfcf-d02c-42f3-80e9-6001a16ef9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name']/iframe</value>
      <webElementGuid>892307dc-95a3-460c-8be8-d852ea95054b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/iframe</value>
      <webElementGuid>75dbaf78-9739-45e6-b364-8313192b00c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-name-h8mxeqginvn00000' and @name = 'card-fields-name-h8mxeqginvn00000' and @src = 'https://checkout.pci.shopifyinc.com/name?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Name on card']</value>
      <webElementGuid>40f0bad6-0ed6-4259-8a9a-ce1760f0ca9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
