<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Security code_card-fields-verificati_98be33</name>
   <tag></tag>
   <elementGuidId>b3ee23e7-240e-42c0-885e-7176c5d6ae2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-verification_value-f8vz7sdo31c00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-verification_value-f8vz7sdo31c00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-verification_value-f8vz7sdo31c00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>271c8850-1fa1-4f0b-997f-51355123e91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>3fb22f34-befa-4276-adf5-cc401ad3540e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>52f60557-ecea-4c65-a749-7a8a75203e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-verification_value-f8vz7sdo31c00000</value>
      <webElementGuid>6dc421ad-aa3e-467d-b954-ebb11ff3f7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-verification_value-f8vz7sdo31c00000</value>
      <webElementGuid>06ce67f8-1260-42fd-aab6-fceb9fdef541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2ae14198-16ce-493e-8ce3-cf1f3857d05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/verification_value?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>017f4e30-20c5-4d82-bb36-43fdf0948dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Security code</value>
      <webElementGuid>db851c9b-5356-4690-be1f-13632a05ad6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-verification_value-f8vz7sdo31c00000&quot;)</value>
      <webElementGuid>7c5a66fd-fc38-4a09-ae40-a946ae35a9df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-verification_value-f8vz7sdo31c00000']</value>
      <webElementGuid>ac1bcc8c-130c-4d0d-bd84-f8346b649819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='verification_value']/iframe</value>
      <webElementGuid>5b7c32ee-b030-4c94-98b7-d7066cb1ffbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/iframe</value>
      <webElementGuid>5a1011f7-ff9e-4244-a393-15bc4508cf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-verification_value-f8vz7sdo31c00000' and @name = 'card-fields-verification_value-f8vz7sdo31c00000' and @src = 'https://checkout.pci.shopifyinc.com/verification_value?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Security code']</value>
      <webElementGuid>cc9b7ffd-8bd6-4102-afd2-7f56c3f0ad41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
