<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Security code_card-fields-verificati_98be33</name>
   <tag></tag>
   <elementGuidId>b3ee23e7-240e-42c0-885e-7176c5d6ae2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-verification_value-f8vz7sdo31c00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-verification_value-f8vz7sdo31c00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-verification_value-f8vz7sdo31c00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>11f4cad6-08b3-4474-98aa-f347fcae041d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>8ce12c18-80ba-4554-99dc-2fada1ab900c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ede355b7-7a5f-4d18-9034-c7a155cb033c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-verification_value-f8vz7sdo31c00000</value>
      <webElementGuid>791444f3-d9c9-405a-a67f-4787d29097f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-verification_value-f8vz7sdo31c00000</value>
      <webElementGuid>0dc455f4-82b7-4784-abc7-3d0f7d7846d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cd3d5e8b-66de-4f27-ae60-5b7bd1301b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/verification_value?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>705943f8-0ae1-4d72-b49b-ccc7ba673c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Security code</value>
      <webElementGuid>0dfc3752-a601-4bba-bd12-95112af32fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-verification_value-f8vz7sdo31c00000&quot;)</value>
      <webElementGuid>eb1288f0-b866-4512-a49e-bce0a6d7705a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-verification_value-f8vz7sdo31c00000']</value>
      <webElementGuid>8caf27a8-7a16-40ad-9895-d63d7ff72e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='verification_value']/iframe</value>
      <webElementGuid>d5d75325-e8cb-4b55-a152-77e8b985abd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/iframe</value>
      <webElementGuid>2375cf11-1fe7-4197-ba0f-ed005f14029d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-verification_value-f8vz7sdo31c00000' and @name = 'card-fields-verification_value-f8vz7sdo31c00000' and @src = 'https://checkout.pci.shopifyinc.com/verification_value?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Security code']</value>
      <webElementGuid>a8bcc21e-bba4-4214-8498-0948231c6912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
