<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card number_card-fields-number-ppcts_b047fd</name>
   <tag></tag>
   <elementGuidId>f84507bb-16d5-47a7-9b3a-4c647f8ae9cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-number-ppcts0wn58000000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-number-ppcts0wn58000000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-number-ppcts0wn58000000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7588620c-fc19-4349-91d5-ba4ff96597d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>d6efe4a5-1afd-4957-be80-26baca95cefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de9e0560-14ee-4823-af28-bbff2e24ed63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-number-ppcts0wn58000000</value>
      <webElementGuid>a5160956-94f4-495d-a819-18efadc02e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-number-ppcts0wn58000000</value>
      <webElementGuid>56302064-fe1e-4747-ac8c-e56f2ccd5a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a0cd8906-2d9f-4762-a875-8d1138298b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/number?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>187a430c-8604-4a81-8375-7251a16b55a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Card number</value>
      <webElementGuid>cfb4e7eb-fef3-49e4-a74f-b7781e7c6500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-number-ppcts0wn58000000&quot;)</value>
      <webElementGuid>7064420e-239a-4c10-863e-9aff67fabf34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-number-ppcts0wn58000000']</value>
      <webElementGuid>8dcb0a81-dd3e-4aaa-8f77-afe38e463e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='number']/iframe</value>
      <webElementGuid>762a2e41-9ef9-4166-9e23-d9b2e5aac8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c4e5dd98-f759-437b-b9a5-6e7e4f2372d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-number-ppcts0wn58000000' and @name = 'card-fields-number-ppcts0wn58000000' and @src = 'https://checkout.pci.shopifyinc.com/number?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Card number']</value>
      <webElementGuid>39beb98a-ff09-4968-8419-29c32b37a189</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
