<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Name on card_card-fields-name-p7oyqf_89c151</name>
   <tag></tag>
   <elementGuidId>6919a98a-7b4b-42f5-96d0-81849e97414c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-name-p7oyqfjv79n00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-name-p7oyqfjv79n00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-name-p7oyqfjv79n00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2f22209c-c09e-415d-ae23-4b56bf794a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>1c39f99e-20f1-42ac-aefa-bc5a795d672f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7204465b-1254-48aa-b3ae-e170d1c985e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-name-p7oyqfjv79n00000</value>
      <webElementGuid>a93695f7-0bab-4217-8aec-48d3c3f8ff77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-name-p7oyqfjv79n00000</value>
      <webElementGuid>a5fa9b79-7e6a-4960-bc85-44c486ba602e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1d3fde37-33da-42be-a7aa-1c17fa6f04de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/name?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>1443e533-a0c3-418e-8933-90a832e84d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Name on card</value>
      <webElementGuid>ca1bb003-b51e-4589-8a4c-127c6600cb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-name-p7oyqfjv79n00000&quot;)</value>
      <webElementGuid>bea6a239-65f4-4775-ab3d-6a1ec131dddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-name-p7oyqfjv79n00000']</value>
      <webElementGuid>d21a3f86-6410-41cb-ac14-a52afeeaecdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name']/iframe</value>
      <webElementGuid>48ce0872-cfbd-4295-ac65-01339893fc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/iframe</value>
      <webElementGuid>93db3248-4b97-4754-80b0-3dc13ed40e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-name-p7oyqfjv79n00000' and @name = 'card-fields-name-p7oyqfjv79n00000' and @src = 'https://checkout.pci.shopifyinc.com/name?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Name on card']</value>
      <webElementGuid>23dae9ea-ea5a-49ed-9c60-e27f6b66bf3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
