<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Expiration date (MM  YY)_card-fields_d66788</name>
   <tag></tag>
   <elementGuidId>e141e62d-dee7-432c-99ae-4f4559f8291b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-expiry-zsrnz5pk1h000000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-expiry-zsrnz5pk1h000000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-expiry-zsrnz5pk1h000000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8aad4755-82bc-4f2b-9e9c-6b6568d87ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>849be779-1934-4e2e-84fb-18f703209142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d50c027-c560-48cd-9346-582415c558ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-expiry-zsrnz5pk1h000000</value>
      <webElementGuid>5ddc7b72-e3e4-4591-846f-e927717056cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-expiry-zsrnz5pk1h000000</value>
      <webElementGuid>d8303981-e7a4-4463-b9a8-3e205a64ba1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9cec3d20-cb2a-4e3d-b364-d0536aef5dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/expiry?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>1ecb3a30-df16-4a26-b471-df215e6ce72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Expiration date (MM / YY)</value>
      <webElementGuid>dac66a7e-f6bb-48de-9569-f10af08e8165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-expiry-zsrnz5pk1h000000&quot;)</value>
      <webElementGuid>ad9cdd0e-3e2e-4b8d-a187-e12dd784c570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-expiry-zsrnz5pk1h000000']</value>
      <webElementGuid>d9361453-b4fb-40b5-9e7d-e1dc5d7d4dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expiry']/iframe</value>
      <webElementGuid>b4a5bd04-e409-4727-9890-38906657f902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/iframe</value>
      <webElementGuid>206d7fbb-0368-4c62-8132-c9e893d0a787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-expiry-zsrnz5pk1h000000' and @name = 'card-fields-expiry-zsrnz5pk1h000000' and @src = 'https://checkout.pci.shopifyinc.com/expiry?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Expiration date (MM / YY)']</value>
      <webElementGuid>de35bd95-8c28-4c1b-b7c4-5ab79f317427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
