<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Name on card_card-fields-name-h8mxeq_b22138</name>
   <tag></tag>
   <elementGuidId>8311008c-15ec-47a2-a85f-2b599a30364b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-name-h8mxeqginvn00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-name-h8mxeqginvn00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-name-h8mxeqginvn00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>09e95c61-d719-47d3-b584-6ac0789ca96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>e3ceec56-174d-412e-aaab-2706cdcf3e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c58c3ddc-24b7-4342-85ff-2189c75c07e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-name-h8mxeqginvn00000</value>
      <webElementGuid>a07c3817-ac32-468d-b72b-d609ed400071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-name-h8mxeqginvn00000</value>
      <webElementGuid>94479b72-1b8b-4722-979b-107d12a0fb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>53d2c9fd-51f3-432e-a436-1e33ac1ddb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/name?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>ad43c40a-3c36-4751-aa6d-0b710c896486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Name on card</value>
      <webElementGuid>bc67b6f6-5cdf-4467-b9fe-6bbcaa94f0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-name-h8mxeqginvn00000&quot;)</value>
      <webElementGuid>84d139d0-7227-4218-a4c0-badeab0d5409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-name-h8mxeqginvn00000']</value>
      <webElementGuid>27faf040-10db-408a-ad1c-f25cea8ec0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name']/iframe</value>
      <webElementGuid>066e80f9-fb11-4920-8e1f-d025f6dadf65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/iframe</value>
      <webElementGuid>7dcf3e9a-849f-4e98-827f-6ddd17218c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-name-h8mxeqginvn00000' and @name = 'card-fields-name-h8mxeqginvn00000' and @src = 'https://checkout.pci.shopifyinc.com/name?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Name on card']</value>
      <webElementGuid>ffff541a-db29-464f-a56b-e95a7e0a680c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
