<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card number_card-fields-number-lcd5o_0c6f78</name>
   <tag></tag>
   <elementGuidId>37b48c0a-763f-429b-ac65-ad508017a0bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-number-lcd5o9hn76k00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-number-lcd5o9hn76k00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-number-lcd5o9hn76k00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f800afa8-26c4-49e8-a800-4f8efdec293b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>d8e96d4c-8bfc-44de-a8b5-93cd48dff50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>65eb0d71-6642-430f-88fa-7ddda2f66c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-number-lcd5o9hn76k00000</value>
      <webElementGuid>f9e27841-6158-42b9-9f45-70def6e4d0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-number-lcd5o9hn76k00000</value>
      <webElementGuid>d658febc-5055-4eae-817d-f22ca3119af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a9a64de5-b75e-4545-9cc9-5ad891ea39fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/number?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>eaaca417-edf3-4eb7-a9c4-692bbf04a137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Card number</value>
      <webElementGuid>d7ee8607-2b93-462e-9f1a-6828e6770171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-number-lcd5o9hn76k00000&quot;)</value>
      <webElementGuid>de605068-4d07-4d09-8f72-0f582d1158fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-number-lcd5o9hn76k00000']</value>
      <webElementGuid>fe7b4235-8002-435e-a766-c34a0c649b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='number']/iframe</value>
      <webElementGuid>e6f054f4-612d-482f-84b3-dd122f04f58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d0d08806-89ed-4b26-bfc2-20cb4342daed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-number-lcd5o9hn76k00000' and @name = 'card-fields-number-lcd5o9hn76k00000' and @src = 'https://checkout.pci.shopifyinc.com/number?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Card number']</value>
      <webElementGuid>4b7f7d2e-6b07-4cee-a380-70a16bb3db88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
