<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration date (MM  YY)_expiry (2)</name>
   <tag></tag>
   <elementGuidId>7895d5cb-b05f-4486-939e-8866f27ea793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;expiry&quot;)[count(. | //input[@autocomplete = 'cc-exp' and @id = 'expiry' and @name = 'expiry' and @type = 'text' and @inputmode = 'numeric' and @pattern = '[0-9]*' and @aria-describedby = 'error-for-expiry tooltip-for-expiry' and @data-current-field = 'expiry' and @class = 'input-placeholder-color--lvl-22' and @placeholder = 'Expiration date (MM / YY)' and @ref_element = 'Object Repository/Page_Checkout - Threads/iframe_Expiration date (MM  YY)_card-fields_b2acd2']) = count(//input[@autocomplete = 'cc-exp' and @id = 'expiry' and @name = 'expiry' and @type = 'text' and @inputmode = 'numeric' and @pattern = '[0-9]*' and @aria-describedby = 'error-for-expiry tooltip-for-expiry' and @data-current-field = 'expiry' and @class = 'input-placeholder-color--lvl-22' and @placeholder = 'Expiration date (MM / YY)' and @ref_element = 'Object Repository/Page_Checkout - Threads/iframe_Expiration date (MM  YY)_card-fields_b2acd2'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Expiration date (MM / YY)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>334ac9eb-9fb7-446e-9c14-aafdbfae6052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>a5ab216b-953f-42bd-9fb4-da42e739501a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>c961d4dc-8918-469a-a45f-dd8855940e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>b24f4d76-f80c-4f69-b92e-47fc259349c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a013d36-eacd-4adf-9d06-8d3a5e24a79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>a5c179f3-dbc9-4d0e-9ce4-e28e10695b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>31124911-590e-47ce-8153-7dea24d60685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>error-for-expiry tooltip-for-expiry</value>
      <webElementGuid>1b64d9fc-23a5-4082-97e8-05268a6d0c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-current-field</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>159dc7b5-b9c3-4417-ae66-6205d72a63d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-placeholder-color--lvl-22</value>
      <webElementGuid>4e01d7e3-2dab-4291-bfd4-9020aa41cbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiration date (MM / YY)</value>
      <webElementGuid>97ca7050-76ce-4787-9a85-202761fc2344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry&quot;)</value>
      <webElementGuid>29c585b9-7b9c-4c25-b565-368188699973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Threads/iframe_Expiration date (MM  YY)_card-fields_b2acd2</value>
      <webElementGuid>99487565-d4e5-4813-8477-ddde00e90c17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expiry']</value>
      <webElementGuid>8246c840-503f-4b3c-9299-5271c2e53c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>811ed49c-17e0-4446-af89-768d99492da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expiry' and @name = 'expiry' and @type = 'text' and @placeholder = 'Expiration date (MM / YY)']</value>
      <webElementGuid>f6e48d04-3b05-4aff-9250-868743aa489d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
