<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Security code_verification_value (3)</name>
   <tag></tag>
   <elementGuidId>d534329d-9a83-4e97-9f40-e484f9a68c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verification_value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verification_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Security code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96447b2b-2476-4b26-9d25-73716a4d419c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-csc</value>
      <webElementGuid>b00e3d41-2218-48c7-9545-2e6f762d7e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verification_value</value>
      <webElementGuid>025b5bd7-8260-4391-9981-595ce13cc4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verification_value</value>
      <webElementGuid>46e288de-45e1-4780-8646-9c2e9ea55042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8385e8a1-f7aa-4cd8-84f3-fe7ef50d1acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>6043092c-9885-4182-8675-bf37b7dc1355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>47623ae1-5e5c-44fa-bbb2-6493e6509457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>error-for-verification_value tooltip-for-verification_value</value>
      <webElementGuid>d2a1e905-1210-4c5a-9d0f-fabc1295499f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-current-field</name>
      <type>Main</type>
      <value>verification_value</value>
      <webElementGuid>5c03fb4c-acef-4a6c-842c-14f846b8b1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-placeholder-color--lvl-22</value>
      <webElementGuid>e546b628-d474-48d1-b74a-3ba190541c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Security code</value>
      <webElementGuid>f805734a-1d95-4654-a720-59f999d2c3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verification_value&quot;)</value>
      <webElementGuid>39b7cd27-243e-46a3-a310-fa4c996ffab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Threads/iframe_Security code_card-fields-verificati_98be33</value>
      <webElementGuid>37d612d9-9f00-4a72-9692-e40147179237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verification_value']</value>
      <webElementGuid>daa409e2-cb10-41d6-beec-7d2006c025e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>54777f3a-7763-430b-9fca-5fcba2772be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verification_value' and @name = 'verification_value' and @type = 'text' and @placeholder = 'Security code']</value>
      <webElementGuid>cc1cc2ad-7b34-4c7b-b8ef-87e76bde61ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
