<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration date (MM  YY)_expiry (2)</name>
   <tag></tag>
   <elementGuidId>7895d5cb-b05f-4486-939e-8866f27ea793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expiry']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;expiry&quot;)[count(. | //input[@autocomplete = 'cc-exp' and @id = 'expiry' and @name = 'expiry' and @type = 'text' and @inputmode = 'numeric' and @pattern = '[0-9]*' and @aria-describedby = 'error-for-expiry tooltip-for-expiry' and @data-current-field = 'expiry' and @class = 'input-placeholder-color--lvl-22' and @placeholder = 'Expiration date (MM / YY)' and @ref_element = 'Object Repository/Page_Checkout - Threads/iframe_Expiration date (MM  YY)_card-fields_b2acd2']) = count(//input[@autocomplete = 'cc-exp' and @id = 'expiry' and @name = 'expiry' and @type = 'text' and @inputmode = 'numeric' and @pattern = '[0-9]*' and @aria-describedby = 'error-for-expiry tooltip-for-expiry' and @data-current-field = 'expiry' and @class = 'input-placeholder-color--lvl-22' and @placeholder = 'Expiration date (MM / YY)' and @ref_element = 'Object Repository/Page_Checkout - Threads/iframe_Expiration date (MM  YY)_card-fields_b2acd2'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Expiration date (MM / YY)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>370730dd-abca-465d-81a0-ac636e20ca04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>6b09c6af-ce42-4227-9789-ad8ef312318e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>90dc9888-78bb-4909-bcf0-872c71e85e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>a77cae5c-aa2e-4e3f-b31e-6ed5ee8c0ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bedb3c02-d9e9-40a2-8dc0-b7e8c2aafd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>ef0dc381-84ac-45fa-ba39-cfdb42204017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>88539802-4e1c-403b-9d68-8a59ba9df1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>error-for-expiry tooltip-for-expiry</value>
      <webElementGuid>30e5ec19-c2e3-461b-bc7e-a388719abb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-current-field</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>ef24be6e-ab30-44c3-aab8-740f4d8b480f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-placeholder-color--lvl-22</value>
      <webElementGuid>75ed3759-a2ca-4923-bfaa-79d95693c410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiration date (MM / YY)</value>
      <webElementGuid>654b0729-9b40-4e66-a900-ab1ea4c584e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry&quot;)</value>
      <webElementGuid>dc0f1b0f-5fd0-43f6-beff-643957f216cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Threads/iframe_Expiration date (MM  YY)_card-fields_b2acd2</value>
      <webElementGuid>38956c09-d93f-4843-adcc-28b8c35fe1e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expiry']</value>
      <webElementGuid>b7f20cb7-cfb6-4de5-b8c4-be84a1c1162d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>70b41cc9-521c-43ee-8fd2-61254c82c4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expiry' and @name = 'expiry' and @type = 'text' and @placeholder = 'Expiration date (MM / YY)']</value>
      <webElementGuid>f3f863c1-638a-4fd3-96d1-de5ec55c0733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
