<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose a delivery method_delivery_strategies</name>
   <tag></tag>
   <elementGuidId>cf3bb641-4c82-44ad-887c-b8b12c21df84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_strategies-SHIPPING</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_strategies-SHIPPING']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ship&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd7477c1-bb7e-4afc-a761-2e34f136bc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>47c3f46f-a018-4a8b-aa4b-1854f22a17cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_strategies-SHIPPING</value>
      <webElementGuid>457be415-020a-47de-8ce6-fe088affefa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_strategies</value>
      <webElementGuid>e4cfea11-8d8f-4e65-97c4-523a78eef0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6hzjvo4 _6hzjvo3 _1fragemnk _1fragem1y _1fragemsf _1fragems9 _1fragemsm _6hzjvog _6hzjvo8 _6hzjvo6 _1fragemsy _6hzjvof _6hzjvoc</value>
      <webElementGuid>21429ccf-427f-4973-9a51-02c732273615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_strategies-SHIPPING&quot;)</value>
      <webElementGuid>5ef90492-256b-4f54-ac44-325b130976f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_strategies-SHIPPING']</value>
      <webElementGuid>53b4cb2b-9ff8-443c-a317-46355842a41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='delivery_strategies']/div/div/div/div/input</value>
      <webElementGuid>2ced3a5a-93d7-4488-9281-e730520caf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div/input</value>
      <webElementGuid>143ffd0e-e032-4fab-85e4-99d3836605c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'delivery_strategies-SHIPPING' and @name = 'delivery_strategies']</value>
      <webElementGuid>4ebf58ed-c5dc-415a-8861-6aa3da9f10c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
