<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration date (MM  YY)_expiry (4)</name>
   <tag></tag>
   <elementGuidId>86db1c69-2754-4d8c-9005-ec61880299ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Expiration date (MM / YY)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>375cabe6-7fdc-4444-9d7f-a6a7cf44c3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>e9322384-6403-426c-bb65-a6920d7377e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>a4a22a03-f456-4e7b-915f-31ecf2cca66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>0b56a0bd-ef07-4083-b4d1-2d59acbc0a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6397b04d-f054-4f0c-8d6a-7cf1b860a5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>e806d327-c33c-4a46-a34f-f29f142ff45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>a07d26f0-94f2-4a3a-a45a-ab7cc8d502fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>error-for-expiry tooltip-for-expiry</value>
      <webElementGuid>488aacab-47fa-4780-ad15-938efe59af75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-current-field</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>837ebd1b-ed56-4a34-b5be-126a249d1d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-placeholder-color--lvl-22</value>
      <webElementGuid>10b9d80b-a592-460d-bef6-1a4d05e07964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiration date (MM / YY)</value>
      <webElementGuid>04fff3a7-0e5f-4f7d-a9e0-e03093c2ea5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry&quot;)</value>
      <webElementGuid>74073af9-8cfb-4762-bda8-416b4354effc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Shopping Cart/Order Summary/Page_Checkout - Threads/iframe_Expiration date (MM  YY)_card-fields_549106</value>
      <webElementGuid>70f31ea3-76f4-43fe-81bb-e96d0cd133eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Checkout - Threads/iframe_Expiration date (MM  YY)_card-fields_549106</value>
      <webElementGuid>8e05ef21-24f3-4fcb-83c2-af3de555fe23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expiry']</value>
      <webElementGuid>21406ce0-9cd9-4eb7-8eed-092af3262aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>52aab26d-8c99-4e92-bfd7-9b1ecc4b7d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expiry' and @name = 'expiry' and @type = 'text' and @placeholder = 'Expiration date (MM / YY)']</value>
      <webElementGuid>13d5a669-d9ef-4aad-95c4-05b92d5924d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
