<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose a delivery method_delivery_strategies</name>
   <tag></tag>
   <elementGuidId>cf3bb641-4c82-44ad-887c-b8b12c21df84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_strategies-SHIPPING</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_strategies-SHIPPING']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ship&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b882213-a040-4f3f-8c62-91c6b1c9e9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>849c7179-5f83-4aa5-abd5-e4f0fba6bb45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_strategies-SHIPPING</value>
      <webElementGuid>3dc55fcd-e4a0-4550-9513-963d1387085e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_strategies</value>
      <webElementGuid>6e4441e8-2ee0-42bc-8c68-fc927e863fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6hzjvo4 _6hzjvo3 _1fragemnk _1fragem1y _1fragemsf _1fragems9 _1fragemsm _6hzjvog _6hzjvo8 _6hzjvo6 _1fragemsy _6hzjvof _6hzjvoc</value>
      <webElementGuid>a2875ac5-f08f-4c77-9834-29a9a1cdc2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_strategies-SHIPPING&quot;)</value>
      <webElementGuid>b58475cc-a8cb-422d-9127-f8f112843739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_strategies-SHIPPING']</value>
      <webElementGuid>29ef6777-9fb7-4047-84e9-f761ed456085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='delivery_strategies']/div/div/div/div/input</value>
      <webElementGuid>3ac9cd04-4b98-4560-9fc3-4e0a29b62269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/div/input</value>
      <webElementGuid>09b92b73-7286-48ff-a319-e5abc3b6dbbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'delivery_strategies-SHIPPING' and @name = 'delivery_strategies']</value>
      <webElementGuid>d715423e-f5cf-47ca-94b4-c2d79c140fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
