<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Check out</name>
   <tag></tag>
   <elementGuidId>5ce5543a-8084-4dee-b215-75c43e67117e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Check out&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2a12960-a05f-410b-a3cb-367550a4fe38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1dbdb529-2035-43f4-a813-8a0a44c500c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout</value>
      <webElementGuid>e5d57bc4-086c-40fe-8877-c95712a4ad06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart__checkout-button button</value>
      <webElementGuid>8e3fb559-4549-45b0-b47d-1d26c8b9891d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkout</value>
      <webElementGuid>09e49432-2573-4315-8e89-abcf1b4df044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>cart</value>
      <webElementGuid>1ef6a7d5-03d5-46d9-a791-88ec0bf1b3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Check out
                </value>
      <webElementGuid>dfd5ef4a-2ee7-4694-9480-84d1cd26edd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout&quot;)</value>
      <webElementGuid>9c422c9b-7fff-4a31-9451-73e736249a77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkout']</value>
      <webElementGuid>99d77848-b606-44e2-b52d-7ce3c750a1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-cart-footer']/div/div/div/div[2]/button</value>
      <webElementGuid>fbc61f5e-fe88-45a0-b9db-e680504eb18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taxes, discounts and shipping calculated at checkout.'])[1]/following::button[1]</value>
      <webElementGuid>c82ad358-4e7a-4daf-ad9f-ba3006c0feb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated total'])[1]/following::button[1]</value>
      <webElementGuid>6ebd8301-e210-4b91-8420-03876da3c583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get exclusive offers'])[1]/preceding::button[1]</value>
      <webElementGuid>f2b6e397-de87-4447-bb0f-a8a319361466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::button[1]</value>
      <webElementGuid>027de99f-73ad-4aaf-b505-9f73135f4ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/button</value>
      <webElementGuid>d0291514-2c39-41fe-b606-7fb720da33ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'checkout' and @name = 'checkout' and @form = 'cart' and (text() = '
                  Check out
                ' or . = '
                  Check out
                ')]</value>
      <webElementGuid>61ce348a-6019-434a-9ca1-a410871ab5cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
