<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Discount code_reductions</name>
   <tag></tag>
   <elementGuidId>6827b34c-5072-46ef-b3ec-67883c9bae67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReductionsInput0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReductionsInput0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Discount code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>797bb63a-b3ce-41bd-9538-041062674dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReductionsInput0</value>
      <webElementGuid>096e2b5e-fcc9-4a6e-a02d-c1c6327cf06d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reductions</value>
      <webElementGuid>285bb76c-32b1-449c-b879-7f8252106969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Discount code</value>
      <webElementGuid>f6cd105b-1c89-4470-b152-5ee19eb81276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e424e6b4-3848-4c30-9b57-dce79f971b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ReductionsInput0-label</value>
      <webElementGuid>15521047-7ae1-46a9-be74-18a8357b71db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7ozb2uq _7ozb2up _1fragemlj _1fragemst _1fragemod _1fragemrz _7ozb2ut _7ozb2us _1fragemsf _1fragemsa _1fragemsp _7ozb2u11 _7ozb2u1h _7ozb2ur</value>
      <webElementGuid>96a822cb-a1f7-4321-973b-d6ad6f802353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReductionsInput0&quot;)</value>
      <webElementGuid>56b7407f-d517-4612-9508-3dd9432df50c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReductionsInput0']</value>
      <webElementGuid>8e51de61-c80c-49b9-bd31-acb11762f34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form0']/div/div/div/div/div/input</value>
      <webElementGuid>edc9dcbc-bf1f-4667-9f0b-f4b3bd078917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>53b12398-5019-449b-a7fb-906c61659007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReductionsInput0' and @name = 'reductions' and @placeholder = 'Discount code' and @type = 'text']</value>
      <webElementGuid>2146839a-dfe8-410f-a96f-787792b74e0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
