<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Rs. 236.00</name>
   <tag></tag>
   <elementGuidId>25b58a80-6dbb-4b21-951d-d643543229ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-cart-footer']/div/div[2]/div/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.totals__total-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Rs. 236.00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3216aec5-714f-48e8-bc17-6922a1fe0d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>totals__total-value</value>
      <webElementGuid>a234abb6-1af8-4273-af3f-8d6f55a742dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rs. 236.00</value>
      <webElementGuid>d4f0559f-d026-4cce-8393-9a153101b298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-cart-footer&quot;)/div[@class=&quot;page-width&quot;]/div[@class=&quot;cart__footer isolate section-template--18610480480479__cart-footer-padding&quot;]/div[@class=&quot;cart__blocks&quot;]/div[@class=&quot;js-contents&quot;]/div[@class=&quot;totals&quot;]/p[@class=&quot;totals__total-value&quot;]</value>
      <webElementGuid>7b57217d-4d0c-4977-bb90-7400de688bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-cart-footer']/div/div[2]/div/div/div[2]/p</value>
      <webElementGuid>3380497c-41d2-4db0-aa18-a3fdad53f923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated total'])[1]/following::p[1]</value>
      <webElementGuid>bc843fda-d65a-4baf-a00d-79fcb4fc46e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹24.00'])[1]/following::p[1]</value>
      <webElementGuid>50ba112e-3415-4be6-a5a4-c81c654792d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taxes, discounts and shipping calculated at checkout.'])[1]/preceding::p[1]</value>
      <webElementGuid>3ea32fea-3f68-4188-987d-f488cd614ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check out'])[2]/preceding::p[1]</value>
      <webElementGuid>068172ea-ff4e-4615-a51c-b828f43f82fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rs. 236.00']/parent::*</value>
      <webElementGuid>b69c7db7-3855-48fe-940b-24975fc45ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/p</value>
      <webElementGuid>fc614ec0-74a7-4fbc-9e5d-f3e363aba1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Rs. 236.00' or . = 'Rs. 236.00')]</value>
      <webElementGuid>c40302fa-93b1-4a1f-ac53-e6b4bef8275e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
