<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>782872e4-ea63-4018-a1cc-a00636a0ffec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._5uqybw2._5uqybw1._1fragem28._1fragemkp._1fragem46._1fragem5z._1fragemm8._1fragemmc._1fragem73 > button._1m2hr9ge._1m2hr9gd._1fragemsq._1fragemlj._1fragemnk._1fragem2i._1fragems4._1fragemsg._1fragemsl._1fragemsa._1m2hr9g1h._1m2hr9g1d._1fragemne._1m2hr9g16._1m2hr9g13._1fragemop._1fragemon._1fragemor._1fragemol._1fragempl._1fragemph._1fragempp._1fragempd._1fragemb4._1fragemaf._1fragembt._1fragem9q._1fragemsa._1m2hr9g1q._1m2hr9g1o._1m2hr9g10._1m2hr9gx._1m2hr9g1b._1m2hr9g19._1fragems5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b48fa88-b46e-4329-bc32-a54b915fbe6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>02570d3c-40f4-424b-adbf-0a9656f84664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>Form2</value>
      <webElementGuid>6c7931ca-2588-4895-a430-1afd5dde6d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1m2hr9ge _1m2hr9gd _1fragemsq _1fragemlj _1fragemnk _1fragem2i _1fragems4 _1fragemsg _1fragemsl _1fragemsa _1m2hr9g1h _1m2hr9g1d _1fragemne _1m2hr9g16 _1m2hr9g13 _1fragemop _1fragemon _1fragemor _1fragemol _1fragempl _1fragemph _1fragempp _1fragempd _1fragemb4 _1fragemaf _1fragembt _1fragem9q _1fragemsa _1m2hr9g1q _1m2hr9g1o _1m2hr9g10 _1m2hr9gx _1m2hr9g1b _1m2hr9g19 _1fragems5</value>
      <webElementGuid>65bca49e-39e6-4167-9bab-c2bbb1c13e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>f07f20d8-f41e-455c-8b21-c8c972728a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Modal0&quot;)/div[@class=&quot;u2pextw u2pextv _1fragem2s _1fragemjq _1fragemk5 u2pextz u2pextx _1fragem3w _1fragem5p&quot;]/div[@class=&quot;u2pext13 u2pext12 _1fragemnq u2pext1o u2pext1n _1fragemiw _1fragemh3 _1fragemd7&quot;]/div[@class=&quot;_1ip0g651 _1ip0g650 _1fragemlj _1fragem3w _1fragem5p _1fragem2s&quot;]/div[@class=&quot;km09ry1 _1fragemlj&quot;]/div[1]/div[@class=&quot;r62YW&quot;]/div[@class=&quot;_1ip0g651 _1ip0g650 _1fragemlj _1fragem3w _1fragem5p _1fragem2s&quot;]/div[@class=&quot;_5uqybw0 _1fragemlj _1fragem28 _1fragem73&quot;]/div[@class=&quot;_5uqybw2 _5uqybw1 _1fragem28 _1fragemkp _1fragem46 _1fragem5z _1fragemm8 _1fragemmc _1fragem73&quot;]/button[@class=&quot;_1m2hr9ge _1m2hr9gd _1fragemsq _1fragemlj _1fragemnk _1fragem2i _1fragems4 _1fragemsg _1fragemsl _1fragemsa _1m2hr9g1h _1m2hr9g1d _1fragemne _1m2hr9g16 _1m2hr9g13 _1fragemop _1fragemon _1fragemor _1fragemol _1fragempl _1fragemph _1fragempp _1fragempd _1fragemb4 _1fragemaf _1fragembt _1fragem9q _1fragemsa _1m2hr9g1q _1m2hr9g1o _1m2hr9g10 _1m2hr9gx _1m2hr9g1b _1m2hr9g19 _1fragems5&quot;]</value>
      <webElementGuid>82abd291-aa3d-43f2-b675-b9f8670b5657</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[5]</value>
      <webElementGuid>c206b141-bd4f-49f8-9af5-0d1bdb04e1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Modal0']/div/div/div/div/div/div/div/div[6]/div/button[2]</value>
      <webElementGuid>82942680-0ca5-42b6-b973-1e7902f0e883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>7238a2ec-51bc-4ae8-b795-b4aecda0616b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIN code'])[1]/following::button[2]</value>
      <webElementGuid>cc71d88c-00c8-4dea-8a5f-4581b83ec1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/button[2]</value>
      <webElementGuid>d3e9f7ed-5a47-4d46-8e11-dd4f257dc7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @form = 'Form2' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>176bc8eb-20ef-4bb9-92c8-e39d378a46b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
