<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>cc2c16c5-1dd3-4d82-8246-ce9fb7eb1d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button._1m2hr9ge._1m2hr9gd._1fragemsq._1fragemlj._1fragemnk._1fragem2i._1fragems4._1fragemsg._1fragemsl._1fragemsa._1m2hr9g18._1m2hr9g15._1fragemsg._1fragemsl._1fragemry._1m2hr9g12._1m2hr9g11._1fragemri._1m2hr9g1b._1m2hr9g19._1fragems5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Edit address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f19c09b1-2754-4cac-8440-56be38a91ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>afae8369-a44a-4ebc-b416-1067a02a170d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Edit address</value>
      <webElementGuid>4a398e73-e794-4415-86d7-88bb555f2511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1m2hr9ge _1m2hr9gd _1fragemsq _1fragemlj _1fragemnk _1fragem2i _1fragems4 _1fragemsg _1fragemsl _1fragemsa _1m2hr9g18 _1m2hr9g15 _1fragemsg _1fragemsl _1fragemry _1m2hr9g12 _1m2hr9g11 _1fragemri _1m2hr9g1b _1m2hr9g19 _1fragems5</value>
      <webElementGuid>a83a8eb3-2f4b-439e-875f-169bcf58b677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>c117fc2a-774d-426a-a942-449f7be8bf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Overlay4&quot;)/div[@class=&quot;xhuvqp1 xhuvqp0 _1fragem8r _1fragem87 _1fragem9b _1fragem7n _1fragemlj xhuvqp9 xhuvqp5 _1fragemn6 _1fragemna _1fragemsy xhuvqpg xhuvqpd xhuvqpt&quot;]/div[@class=&quot;xhuvqps xhuvqpr _1fragemq7 _1fragemqm _1fragemps _1fragemr1 _1fragemlj _1fragemsv _1fragemsy&quot;]/div[@class=&quot;_1ip0g651 _1ip0g650 _1fragemlj _1fragem3m _1fragem5f _1fragem2s _1fragemof _1fragemev _1fragemgt _1fragemd2 _1fragemim&quot;]/button[@class=&quot;_1m2hr9ge _1m2hr9gd _1fragemsq _1fragemlj _1fragemnk _1fragem2i _1fragems4 _1fragemsg _1fragemsl _1fragemsa _1m2hr9g18 _1m2hr9g15 _1fragemsg _1fragemsl _1fragemry _1m2hr9g12 _1m2hr9g11 _1fragemri _1m2hr9g1b _1m2hr9g19 _1fragems5&quot;]</value>
      <webElementGuid>3d071aa6-2866-4409-8e13-dc7f25e5b1f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>ecea23b0-21b5-4006-90a8-1c6364a7b2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Overlay4']/div/div/div/button</value>
      <webElementGuid>f6940d40-6662-4f71-b2a0-d7cfebfc76fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹76.08'])[1]/following::button[1]</value>
      <webElementGuid>07eb062c-2061-4dbe-89ea-dd2e9d5c913c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INR'])[1]/following::button[1]</value>
      <webElementGuid>38c57705-ebc5-4b7c-9cf8-0ffdbe55be3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/button</value>
      <webElementGuid>4ffebd78-e0ae-4cc6-bea5-8c44317294d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>7e738d9d-6c96-422a-8dde-31d09ed8d95c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
