<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FLEX FIT  MINI OTTOMAN BLACK</name>
   <tag></tag>
   <elementGuidId>f2275501-cebc-4c1d-89ce-d5285c798937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardLink-template--18610480578783__product-grid-8834481979615</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CardLink-template--18610480578783__product-grid-8834481979615']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;FLEX FIT | MINI OTTOMAN BLACK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>76ceef30-88bf-439e-8cce-7ee8b6cd6776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/flex-fit-mini-ottoman-black</value>
      <webElementGuid>d8793a5c-39b5-4a72-a4c6-e552a0f09154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481979615</value>
      <webElementGuid>2e9932e2-0e24-447a-9d37-093085c6693a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>30f453c2-9bb4-435a-8695-23815ff1be1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481979615 Badge-template--18610480578783__product-grid-8834481979615</value>
      <webElementGuid>3bd75321-04c9-4add-97e9-22320eaef5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              FLEX FIT | MINI OTTOMAN BLACK
            </value>
      <webElementGuid>2ae09c3d-2e5c-4ead-a882-19bc0ab41564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink-template--18610480578783__product-grid-8834481979615&quot;)</value>
      <webElementGuid>cddef3af-1749-4dbb-b76a-4b510663fa27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink-template--18610480578783__product-grid-8834481979615']</value>
      <webElementGuid>ace9b484-0591-4de1-90fb-0782bfb53298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title-template--18610480578783__product-grid-8834481979615']/a</value>
      <webElementGuid>7116f9fd-3dc4-479a-9cd5-4f56caa4ccd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'FLEX FIT | MINI OTTOMAN BLACK')])[2]</value>
      <webElementGuid>fb63d5a3-924f-45cb-80b8-2cc4fc0b7fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FLEX FIT | MINI OTTOMAN BLACK'])[1]/following::a[1]</value>
      <webElementGuid>1f43a8c2-65a0-4f30-85bd-4f563be15e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[23]/preceding::a[1]</value>
      <webElementGuid>25a2959c-10dd-4d6f-8d7c-893e9a4bcf88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 29.99'])[1]/preceding::a[1]</value>
      <webElementGuid>fcf94470-baec-4701-8648-b5b9e8adc454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/flex-fit-mini-ottoman-black')])[2]</value>
      <webElementGuid>73397c8d-509c-43a8-83c0-dfa95075c80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/div/div/div[2]/div/h3/a</value>
      <webElementGuid>e457ea97-c8da-4bdf-b8db-65d9206a2cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/flex-fit-mini-ottoman-black' and @id = 'CardLink-template--18610480578783__product-grid-8834481979615' and (text() = '
              FLEX FIT | MINI OTTOMAN BLACK
            ' or . = '
              FLEX FIT | MINI OTTOMAN BLACK
            ')]</value>
      <webElementGuid>dda9bb6c-9967-40b9-b018-96f4df571105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
