<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ASICS TIGER  GEL-LYTE V 30 YEARS OF GEL PACK_1</name>
   <tag></tag>
   <elementGuidId>488c9e21-da31-4250-8e2b-39d92f10a229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/div[2]/div/div/div/div/ul/li[1]/div/div/div[2]/div[1]/div/div/div/div[1]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CardLink-template--18610480578783__product-grid-8834481160415</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ASICS TIGER | GEL-LYTE V '30 YEARS OF GEL' PACK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d56df601-e7cc-454c-a442-91cc18b342f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/asics-tiger-gel-lyte-v-30-years-of-gel-pack?_pos=1&amp;_fid=8f8607fe7&amp;_ss=c</value>
      <webElementGuid>ec27f929-08bf-419d-afc6-7c6ce22617e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481160415</value>
      <webElementGuid>39f0af5d-ef20-49f8-9f72-3ef7d3eec669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>28c403d9-ee1a-4480-9396-cade9eb04322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481160415 Badge-template--18610480578783__product-grid-8834481160415</value>
      <webElementGuid>35619664-ecca-430b-8edd-f7ea7f903706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              ASICS TIGER | GEL-LYTE V '30 YEARS OF GEL' PACK
            </value>
      <webElementGuid>9fb92220-b916-43ff-aaca-af66177840ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink-template--18610480578783__product-grid-8834481160415&quot;)</value>
      <webElementGuid>5911623b-88df-4a72-b451-e5a63c15ead2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink-template--18610480578783__product-grid-8834481160415']</value>
      <webElementGuid>9880fbb6-3dec-45a1-a02b-667d2c737db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title-template--18610480578783__product-grid-8834481160415']/a</value>
      <webElementGuid>3dd5caf6-858b-4327-b44b-306f160fa8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove all'])[3]/following::a[2]</value>
      <webElementGuid>c65af906-528e-4cfc-b229-fc7960127081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[1]/preceding::a[1]</value>
      <webElementGuid>a1c7a84b-a7e5-4eab-87cc-6cf46af2e255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 220.00'])[1]/preceding::a[1]</value>
      <webElementGuid>1f86c84e-1613-4cdc-b259-652f5b9758a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/asics-tiger-gel-lyte-v-30-years-of-gel-pack?_pos=1&amp;_fid=8f8607fe7&amp;_ss=c')])[2]</value>
      <webElementGuid>38edaa22-9887-4b95-85a5-2d791237ebbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3/a</value>
      <webElementGuid>92c4dc0f-6f4c-4418-98fc-ac731623f34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/asics-tiger-gel-lyte-v-30-years-of-gel-pack?_pos=1&amp;_fid=8f8607fe7&amp;_ss=c' and @id = 'CardLink-template--18610480578783__product-grid-8834481160415' and (text() = concat(&quot;
              ASICS TIGER | GEL-LYTE V &quot; , &quot;'&quot; , &quot;30 YEARS OF GEL&quot; , &quot;'&quot; , &quot; PACK
            &quot;) or . = concat(&quot;
              ASICS TIGER | GEL-LYTE V &quot; , &quot;'&quot; , &quot;30 YEARS OF GEL&quot; , &quot;'&quot; , &quot; PACK
            &quot;))]</value>
      <webElementGuid>be9a47bb-bd1b-407a-a6e6-25b66a7d9d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
