<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONVERSE  CHUCK TAYLOR ALL STAR LO</name>
   <tag></tag>
   <elementGuidId>061d5c41-3f71-4fd5-9514-979fc80d3943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardLink-template--18610480578783__product-grid-8834481684703</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CardLink-template--18610480578783__product-grid-8834481684703']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;CONVERSE | CHUCK TAYLOR ALL STAR LO&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b2e4bded-afbb-4cb4-b895-cbd88c137047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/converse-chuck-taylor-all-star-lo</value>
      <webElementGuid>45a0d4d6-67ac-4d82-bb1a-ffe382bb8a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481684703</value>
      <webElementGuid>a99528c3-e4bc-4904-a11d-0c094de39525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>2f2409cb-e2c4-4ac4-ad83-75f7db88ed81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481684703 Badge-template--18610480578783__product-grid-8834481684703</value>
      <webElementGuid>aac343be-42dd-418b-b553-e2044d101ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              CONVERSE | CHUCK TAYLOR ALL STAR LO
            </value>
      <webElementGuid>a750957a-62b1-4ddf-b39f-fe73fdc6630e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink-template--18610480578783__product-grid-8834481684703&quot;)</value>
      <webElementGuid>ac9e7715-e41e-4d32-9794-7550e23ae748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink-template--18610480578783__product-grid-8834481684703']</value>
      <webElementGuid>68f65b24-a0a7-4fe6-92af-c57ea1562612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title-template--18610480578783__product-grid-8834481684703']/a</value>
      <webElementGuid>bb21fc1f-b1f9-46a8-904b-1a5294e39b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CONVERSE | CHUCK TAYLOR ALL STAR LO')])[2]</value>
      <webElementGuid>08d2e518-e63b-4e86-88b7-da4970649b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONVERSE | CHUCK TAYLOR ALL STAR LO'])[1]/following::a[1]</value>
      <webElementGuid>bef8d4d6-ba65-4b58-b71c-4c1f046767ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[13]/preceding::a[1]</value>
      <webElementGuid>10f3877c-7d10-42f6-b821-c08dfada1118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 100.00'])[1]/preceding::a[1]</value>
      <webElementGuid>cc2e776e-c3d0-4bb4-9665-ca56f146f5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/converse-chuck-taylor-all-star-lo')])[2]</value>
      <webElementGuid>3b7d16f8-b6e5-4575-b0c8-bfe751a48ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/div/div[2]/div/h3/a</value>
      <webElementGuid>8f554ae7-c090-40fd-b568-bc33b8968c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/converse-chuck-taylor-all-star-lo' and @id = 'CardLink-template--18610480578783__product-grid-8834481684703' and (text() = '
              CONVERSE | CHUCK TAYLOR ALL STAR LO
            ' or . = '
              CONVERSE | CHUCK TAYLOR ALL STAR LO
            ')]</value>
      <webElementGuid>c5d5c45d-d2f8-498c-882a-04cf1b392f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
