<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card number_card-fields-number-rtul7_dc815b</name>
   <tag></tag>
   <elementGuidId>aeb0bb99-56cf-4752-ace6-defd15718a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-number-rtul7grpx8000000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-number-rtul7grpx8000000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-number-rtul7grpx8000000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d35ab08f-6fce-4cc3-99e8-39585e15f475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>59dcb534-165d-436f-8456-d129227927a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>348c3011-3417-4232-987c-302245689428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-number-rtul7grpx8000000</value>
      <webElementGuid>d5409603-b2ad-403a-9aa3-513401842857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-number-rtul7grpx8000000</value>
      <webElementGuid>b9860357-8339-445c-aadb-09ccfda0c00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>afa390dd-dd0b-422a-bfc3-24244ff57687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/number?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>1ed4e12b-ea38-48bf-ab18-0103403ae3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Card number</value>
      <webElementGuid>cdb26afe-61ab-48c1-9752-ee4204bd9bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-number-rtul7grpx8000000&quot;)</value>
      <webElementGuid>a804c1c7-977e-4fe7-bdff-8e7a852546ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-number-rtul7grpx8000000']</value>
      <webElementGuid>71ae47c3-4958-4aac-a404-0b446b83b21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='number']/iframe</value>
      <webElementGuid>80826fad-baa7-445a-bd88-e6c0e55e79c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b7586578-89a5-442d-9011-403227101bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-number-rtul7grpx8000000' and @name = 'card-fields-number-rtul7grpx8000000' and @src = 'https://checkout.pci.shopifyinc.com/number?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Card number']</value>
      <webElementGuid>481868ba-ee4f-4ccc-a154-9ca7486e8300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
