<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Security code_card-fields-verificati_b60e31</name>
   <tag></tag>
   <elementGuidId>f8d1ce5f-eb0d-48fc-86dc-dd9f9e7e8930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-verification_value-9sfifdopwuv00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-verification_value-9sfifdopwuv00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-verification_value-9sfifdopwuv00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ad339ae4-0707-4b8b-a920-9299c3a2d235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>69948147-8cbb-4bd9-abad-c3ee2ea9be41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e43e92f3-60ed-490d-8826-b16834ca0e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-verification_value-9sfifdopwuv00000</value>
      <webElementGuid>ddf0fd72-f6c5-48ea-9ce5-7e4e7dcc0afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-verification_value-9sfifdopwuv00000</value>
      <webElementGuid>91ec58c4-4b5b-4df4-a1bc-0a2b50e992d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d341d468-9dd5-44f9-8aef-b3685556febf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/verification_value?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>263fa772-0e00-41c5-b9c5-3cb53c2b8bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Security code</value>
      <webElementGuid>e3650826-a78c-4e8a-baa0-141e6990e42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-verification_value-9sfifdopwuv00000&quot;)</value>
      <webElementGuid>14f22f4f-0401-486a-986a-9f6799e1f89a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-verification_value-9sfifdopwuv00000']</value>
      <webElementGuid>c9d1d98b-2d37-4949-9816-4191b13f55ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='verification_value']/iframe</value>
      <webElementGuid>ab94fbf9-ab5d-48f4-aead-6237f35bbd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/iframe</value>
      <webElementGuid>fe645273-84fd-4415-ba3c-b1b07cedce24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-verification_value-9sfifdopwuv00000' and @name = 'card-fields-verification_value-9sfifdopwuv00000' and @src = 'https://checkout.pci.shopifyinc.com/verification_value?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Security code']</value>
      <webElementGuid>68a2e511-45c4-4d4a-82df-544ee9e1ad10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
