<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Expiration date (MM  YY)_card-fields_51ccca</name>
   <tag></tag>
   <elementGuidId>cc09b316-38fd-43f8-8880-52d29ac27ec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card-fields-expiry-o7geyfrwb3p00000</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='card-fields-expiry-o7geyfrwb3p00000']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;card-fields-expiry-o7geyfrwb3p00000&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f210a289-67ac-47ea-9187-0c906093bd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-fields-iframe</value>
      <webElementGuid>a258ff56-8fc7-4466-aa2b-f21b738f8f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5a68bdff-a4b0-4534-9917-0518c654f658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card-fields-expiry-o7geyfrwb3p00000</value>
      <webElementGuid>8db6ca3c-59cb-49c2-904e-f5615c2d6ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card-fields-expiry-o7geyfrwb3p00000</value>
      <webElementGuid>53fb9c77-38ab-44df-9a82-9ef3bdbd3cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7d74298f-69df-4e74-838f-5efd926aa9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.pci.shopifyinc.com/expiry?identifier=&amp;location=&amp;dir=ltr</value>
      <webElementGuid>9f3e1278-9d71-4e8d-accf-b538b55426e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Field container for: Expiration date (MM / YY)</value>
      <webElementGuid>b443ee2c-86cc-493a-9513-cb7c163ca97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-fields-expiry-o7geyfrwb3p00000&quot;)</value>
      <webElementGuid>5069129e-5146-4dc4-90bd-7bc6fd7ac93c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='card-fields-expiry-o7geyfrwb3p00000']</value>
      <webElementGuid>02ad1c69-eef5-4301-9bf3-cd7ba9f1d4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='expiry']/iframe</value>
      <webElementGuid>5fc82c50-0789-4484-9166-d6640751ae3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/iframe</value>
      <webElementGuid>0d4ab3d6-fcee-4f05-b017-73299e299bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'card-fields-expiry-o7geyfrwb3p00000' and @name = 'card-fields-expiry-o7geyfrwb3p00000' and @src = 'https://checkout.pci.shopifyinc.com/expiry?identifier=&amp;location=&amp;dir=ltr' and @title = 'Field container for: Expiration date (MM / YY)']</value>
      <webElementGuid>4d96c620-9837-498b-a648-f4b1d9cc51dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
