<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration date (MM  YY)_expiry (1)</name>
   <tag></tag>
   <elementGuidId>0b827c00-6395-4f62-a553-bd256082d8bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Expiration date (MM / YY)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4f23055-b8e9-4e95-8290-1e644a107e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-exp</value>
      <webElementGuid>e061dc41-56d6-4d05-a9b5-1847d6f6a602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>c3388f73-d33d-4e38-9559-f7aa0b2b7063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>805de35d-c336-4dcf-b2c9-36f4e941c3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85defd4a-d0c6-48ed-91e7-83db82e93ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>103e2e59-5a7d-4cb4-b241-d7ebd3c54b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>7df5047a-08b2-48d4-92b2-10bd691885fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>error-for-expiry tooltip-for-expiry</value>
      <webElementGuid>d6905d41-a238-4580-a3ae-a032de05de11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-current-field</name>
      <type>Main</type>
      <value>expiry</value>
      <webElementGuid>c63ebc5c-1fc3-480a-af4c-9060fd4565c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-placeholder-color--lvl-22</value>
      <webElementGuid>b39a6590-1dbb-45f5-8eab-3f5c8c9792d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Expiration date (MM / YY)</value>
      <webElementGuid>a567c2f4-e10a-4579-998e-6c8047b3a7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expiry&quot;)</value>
      <webElementGuid>c7dbc1a3-5637-4c28-aa7d-ebec5f2239c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Account/Cancel/Page_Checkout - Threads/iframe_Expiration date (MM  YY)_card-fields_13bf8f</value>
      <webElementGuid>f1f31af2-703d-44dc-948e-6c15c548885e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expiry']</value>
      <webElementGuid>cc4be5a7-f64f-4be9-b0ab-eeae2a07beec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>ccd98cbd-adec-4226-a74a-4900eccd7403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expiry' and @name = 'expiry' and @type = 'text' and @placeholder = 'Expiration date (MM / YY)']</value>
      <webElementGuid>c99c82e4-285e-4fb5-bcbc-ab0a5778c50a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
