<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_No results found for invalid search. Chec_5feb15</name>
   <tag></tag>
   <elementGuidId>3ecd9e44-3c8d-4dec-a5be-0dd4452f99f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='shopify-section-template--17877714043048__main']/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;No results found for “invalid search”. Check the spelling or use a different wor&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>af6a84af-3cfc-4c60-910a-8d31543d0609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>cff2cfab-ab49-4b7b-bc16-b0a7a2deea4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No results found for “invalid search”. Check the spelling or use a different word or phrase.</value>
      <webElementGuid>a4cac8b4-5da0-43ec-b5a2-01045935e95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--17877714043048__main&quot;)/div[@class=&quot;template-search template-search--empty section-template--17877714043048__main-padding&quot;]/div[@class=&quot;template-search__header page-width scroll-trigger animate--fade-in&quot;]/p[1]</value>
      <webElementGuid>69641f5f-91b8-4c41-90f2-9c1f78585442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='shopify-section-template--17877714043048__main']/div/div/p</value>
      <webElementGuid>71e9b750-e906-494e-9d19-a8cdbc876728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::p[1]</value>
      <webElementGuid>1eaa80ba-25fc-4ae2-8837-29e5249c49ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search results'])[1]/following::p[1]</value>
      <webElementGuid>ce86e4ba-0579-456d-8da7-53f0b46b0b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe to our emails'])[1]/preceding::p[1]</value>
      <webElementGuid>eac3c7b3-328c-4d0f-aca8-a5ba8960c0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::p[1]</value>
      <webElementGuid>6f8af766-7443-4ab9-864e-d67bf4109574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No results found for “invalid search”. Check the spelling or use a different word or phrase.']/parent::*</value>
      <webElementGuid>3a27e839-5d7d-4412-a3f3-921a7192e134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>25134895-fa5b-46e9-84a5-757f473d7efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'No results found for “invalid search”. Check the spelling or use a different word or phrase.' or . = 'No results found for “invalid search”. Check the spelling or use a different word or phrase.')]</value>
      <webElementGuid>a7c69c66-dd2d-4756-9c74-12ef62b1a0eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
