<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Increase quantity for ADIDAS  CLASSIC _bbf958</name>
   <tag></tag>
   <elementGuidId>adb5b910-bd70-44c9-8a06-51b43f8e70fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sls-custom-radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product-form-template--18610481004767__main']/div/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#product-form-template--18610481004767__main span >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f88db9c-68ae-4534-a628-df00d303d540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sls-custom-radio</value>
      <webElementGuid>5b6c5b0e-2873-4a99-9f11-e4ab05e48db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-form-template--18610481004767__main&quot;)/div[@class=&quot;sealsubs-target-element sealsubs-full&quot;]/div[@class=&quot;sealsubs-container&quot;]/div[@class=&quot;sls-option-container seal-table  sls-active&quot;]/div[@class=&quot;seal-row&quot;]/div[@class=&quot;seal-col seal-col-radio&quot;]/span[@class=&quot;sls-custom-radio&quot;]</value>
      <webElementGuid>412860e2-a029-4377-9d84-7a9946c261b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-form-template--18610481004767__main']/div/div/div/div/div/span</value>
      <webElementGuid>288236a5-bf4b-4a74-85ae-213d978b0fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/span</value>
      <webElementGuid>d67f4570-57a8-4ca2-906b-a4d1b6e37966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
