<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Shirts</name>
   <tag></tag>
   <elementGuidId>b810c7b8-3acd-47c3-9058-7f2dc6222f55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#predictive-search-option-collection-1 > a.predictive-search__item.link.link--text > div.predictive-search__item-content.predictive-search__item-content--centered > p.predictive-search__item-heading.h5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;predictive-search-option-collection-1&quot;]/a/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Shirts&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>37da67ab-88d0-4926-b4aa-c2c5260c8130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>predictive-search__item-heading h5</value>
      <webElementGuid>8768dc11-fb17-4354-9948-427d56a6b1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shirts</value>
      <webElementGuid>b08520e4-85a2-4863-8c78-8fb8c8e4921c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;predictive-search-option-collection-1&quot;)/a[@class=&quot;predictive-search__item link link--text&quot;]/div[@class=&quot;predictive-search__item-content predictive-search__item-content--centered&quot;]/p[@class=&quot;predictive-search__item-heading h5&quot;]</value>
      <webElementGuid>b4935ef1-e042-4ac5-b1c2-a0dece9fc38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='predictive-search-option-collection-1']/a/div/p</value>
      <webElementGuid>dbe72536-acdb-4df3-a237-c53dbd983af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shirt'])[1]/following::p[1]</value>
      <webElementGuid>259e8628-bfe9-4bf1-b83e-45ff9656f4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestions'])[1]/following::p[2]</value>
      <webElementGuid>c53392a1-6c9a-48dd-9f3c-d8e310453936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/preceding::p[2]</value>
      <webElementGuid>2557d380-9d9e-4cd0-b7c7-2b24b6e7dd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search for “Shirt”'])[1]/preceding::p[4]</value>
      <webElementGuid>1a92bf01-31a4-4cf8-92a6-c6f822c4be4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shirts']/parent::*</value>
      <webElementGuid>36674df7-857a-4a2f-87ae-85cedb1d75e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/p</value>
      <webElementGuid>136fd21d-d625-412a-b8e7-7e70bbf948b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Shirts' or . = 'Shirts')]</value>
      <webElementGuid>730694cd-1b9a-46b6-916d-09c1ecc8a485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
