<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search_svg-wrapper</name>
   <tag></tag>
   <elementGuidId>7d32d560-f83d-4467-b6db-af2bbcd54300</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.search__button.field__button > span.svg-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-sections--17877714337960__header']/sticky-header/header/div/details-modal/details/div/div[2]/predictive-search/form/div/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog >> internal:role=button[name=&quot;Search&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd295164-0f3e-4a68-ad2e-fdde24460f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-wrapper</value>
      <webElementGuid>e54a3eab-6875-41a9-b7ca-e898e6568d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-sections--17877714337960__header&quot;)/sticky-header[@class=&quot;header-wrapper color-scheme-1 gradient header-wrapper--border-bottom&quot;]/header[@class=&quot;header header--middle-left header--mobile-center page-width header--has-menu header--has-social header--has-account&quot;]/div[@class=&quot;header__icons header__icons--localization header-localization&quot;]/details-modal[@class=&quot;header__search&quot;]/details[1]/div[@class=&quot;search-modal modal__content gradient&quot;]/div[@class=&quot;search-modal__content search-modal__content-bottom&quot;]/predictive-search[@class=&quot;search-modal__form&quot;]/form[@class=&quot;search search-modal__form&quot;]/div[@class=&quot;field&quot;]/button[@class=&quot;search__button field__button&quot;]/span[@class=&quot;svg-wrapper&quot;]</value>
      <webElementGuid>7fce6bb2-6006-40f9-b1d7-3d117c18ebb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-sections--17877714337960__header']/sticky-header/header/div/details-modal/details/div/div[2]/predictive-search/form/div/button[2]/span</value>
      <webElementGuid>0efc799b-538a-44c1-a1a7-e9d06603efbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::span[2]</value>
      <webElementGuid>602ee590-79da-4322-b8a6-beeebe443796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[2]/following::span[5]</value>
      <webElementGuid>90e18943-24c1-42ce-8226-29eaa59a1b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggestions'])[1]/preceding::span[1]</value>
      <webElementGuid>9da024e2-d140-4e36-be06-e40dfc61cca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shirt'])[1]/preceding::span[1]</value>
      <webElementGuid>03eaae59-2384-4aa6-9a75-3b0c5838e785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>200be43a-d220-4d02-8e15-2d51d77af33f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
