<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View cart (1)</name>
   <tag></tag>
   <elementGuidId>c96bfae4-d8c6-42e6-901f-5224431ed5ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-notification-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cart-notification-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View cart (1)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01ee1b67-28f1-4949-9fa2-94c120478543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart</value>
      <webElementGuid>40d5079e-4f12-4409-917a-baa3d2d1a141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-notification-button</value>
      <webElementGuid>abd4d637-9cce-46b1-b4ed-40ff1b0f45af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--secondary button--full-width</value>
      <webElementGuid>14a0f06b-5424-4900-bc39-bfd4d9ec229e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View cart (1)
</value>
      <webElementGuid>8b5cd379-ae03-45b0-8f9e-444044d74f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-notification-button&quot;)</value>
      <webElementGuid>bf57c43b-eb89-46e0-9e60-b77ebbe272a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cart-notification-button']</value>
      <webElementGuid>e03ffe9a-21c8-4948-8a2a-4837e7afb714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-notification']/div[3]/a</value>
      <webElementGuid>1c4b80da-3dd2-4174-b96f-dac1d0bd7185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View cart (1)')]</value>
      <webElementGuid>990e2653-6713-41be-b19d-f34b3c688a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='white'])[1]/following::a[1]</value>
      <webElementGuid>fdf0200c-b543-43ab-b310-0e4c504b26f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color:'])[1]/following::a[1]</value>
      <webElementGuid>50cd1893-5620-4924-ba54-f487b185744d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check out'])[1]/preceding::a[1]</value>
      <webElementGuid>2e4bf3e1-bf8e-430c-ac7c-fd057ea757a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue shopping'])[1]/preceding::a[1]</value>
      <webElementGuid>e75486f0-69df-4ac5-9db4-949a8a0e93c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View cart (1)']/parent::*</value>
      <webElementGuid>2b592ae6-4de3-4d6d-80cd-ae6a031bc92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/cart')])[2]</value>
      <webElementGuid>842574a7-5af4-4d78-a3f3-9e965661186b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>494294dd-0c97-4db9-94ca-1d2f29564ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cart' and @id = 'cart-notification-button' and (text() = 'View cart (1)
' or . = 'View cart (1)
')]</value>
      <webElementGuid>fea7faab-bb7f-45ea-ab4e-c88fc4da6b4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
