<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Account</name>
   <tag></tag>
   <elementGuidId>2b377877-a9ef-4aa3-8925-86ff979ffcf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-template--18610481135839__main']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.customer__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Account&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>12f01493-2962-4d4c-82f7-836d470994fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>customer__title</value>
      <webElementGuid>509234ec-cfe3-496c-8630-cf4592fe3cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account</value>
      <webElementGuid>a28b167e-c3a4-473d-a086-00333d823935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--18610481135839__main&quot;)/div[@class=&quot;customer account section-template--18610481135839__main-padding&quot;]/div[1]/h1[@class=&quot;customer__title&quot;]</value>
      <webElementGuid>856a11fd-f9e7-421c-93b3-efd5c3c24d91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-template--18610481135839__main']/div/div/h1</value>
      <webElementGuid>6e60c6dc-0bbe-4123-ac9d-d8bf14d1402d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue shopping'])[1]/following::h1[1]</value>
      <webElementGuid>9fb138b6-9830-48de-9324-4bb6ee6bc6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check out'])[1]/following::h1[1]</value>
      <webElementGuid>95c1d7ac-a02c-4304-ad99-7a238d214430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order history'])[1]/preceding::h1[1]</value>
      <webElementGuid>d024b619-f6da-4e69-a4e0-2eeccaf305e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>9559cff7-3c2a-4005-bf95-a15d26bafd5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Account' or . = 'Account')]</value>
      <webElementGuid>f0839592-3a5e-4b86-af02-9b08c391e81c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
