<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADIDAS  SUPERSTAR 80S</name>
   <tag></tag>
   <elementGuidId>838223a4-dbbf-498a-9156-68bbcd353a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardLink-template--18610480578783__product-grid-8834481291487</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CardLink-template--18610480578783__product-grid-8834481291487']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ADIDAS | SUPERSTAR 80S Sale&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc216832-6066-4701-98db-918e48a24fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/adidas-superstar-80s</value>
      <webElementGuid>3446f260-de8f-4150-bbc7-5424e0c00b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481291487</value>
      <webElementGuid>09023fec-d0d1-4584-9bdf-ef6666ca2728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>8e3e364c-32e0-4179-b670-74681c0663af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481291487 Badge-template--18610480578783__product-grid-8834481291487</value>
      <webElementGuid>237cd978-b884-4012-a7f6-41db48db900b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              ADIDAS | SUPERSTAR 80S
            </value>
      <webElementGuid>332ea8a0-20b5-4df2-813b-23109975fee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink-template--18610480578783__product-grid-8834481291487&quot;)</value>
      <webElementGuid>dd83e1d9-f402-49c9-a345-79b9f15207f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink-template--18610480578783__product-grid-8834481291487']</value>
      <webElementGuid>fd9e5c07-8ccf-4e97-88a6-84c24a39eae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title-template--18610480578783__product-grid-8834481291487']/a</value>
      <webElementGuid>e4a2fb5a-1f03-4b3b-81b7-de2023b67738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ADIDAS | SUPERSTAR 80S')])[2]</value>
      <webElementGuid>e2d72bec-dc6c-4ba5-aab2-1798da18f244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale'])[7]/following::a[1]</value>
      <webElementGuid>61f03c1c-3df2-4527-8099-65de8c67b685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADIDAS | SUPERSTAR 80S'])[1]/following::a[1]</value>
      <webElementGuid>6a9b772d-d46c-4241-ba40-c896b8ce1816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[7]/preceding::a[1]</value>
      <webElementGuid>f6540005-0388-4e5a-b792-55166c5015b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 136.00'])[1]/preceding::a[1]</value>
      <webElementGuid>b40aa96b-a636-4f03-8a6f-5d50fd795044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/adidas-superstar-80s')])[2]</value>
      <webElementGuid>bbbb21c7-8641-476b-af30-a61d6cb601ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/div[2]/div/h3/a</value>
      <webElementGuid>01d599a0-861a-44db-a9fc-988ecbe2b7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/adidas-superstar-80s' and @id = 'CardLink-template--18610480578783__product-grid-8834481291487' and (text() = '
              ADIDAS | SUPERSTAR 80S
            ' or . = '
              ADIDAS | SUPERSTAR 80S
            ')]</value>
      <webElementGuid>ed878f88-9dbe-44c0-93f3-de38dcdaa091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
