<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Mens Shirt</name>
   <tag></tag>
   <elementGuidId>a3c6ce98-003a-4376-84d9-21b366358afe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='ProductInfo-template--17877714010280__main']/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Men's Shirt&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a6cf09f7-3c22-45c5-a74b-cc3f578fdfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men's Shirt</value>
      <webElementGuid>b557d64d-4ec7-455f-84d9-389213e40826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductInfo-template--17877714010280__main&quot;)/div[@class=&quot;product__title&quot;]/h1[1]</value>
      <webElementGuid>401149e7-bc65-440b-be85-cb76e5415e95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='ProductInfo-template--17877714010280__main']/div/h1</value>
      <webElementGuid>0bec390b-920d-4ed0-a725-5cbd74d6cd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[1]/following::h1[1]</value>
      <webElementGuid>294cbabe-b9d6-4ff8-b098-c5252fef86b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open media 4 in modal'])[1]/following::h1[1]</value>
      <webElementGuid>14e41afb-133f-4bb3-99cd-a876f43851c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[1]/preceding::h1[1]</value>
      <webElementGuid>694c5586-dd9e-48e3-9eea-88a97830fc3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b5829b62-f318-499f-b163-0ab78d28f33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = concat(&quot;Men&quot; , &quot;'&quot; , &quot;s Shirt&quot;) or . = concat(&quot;Men&quot; , &quot;'&quot; , &quot;s Shirt&quot;))]</value>
      <webElementGuid>18737326-d04d-40e0-9ace-6ba7cdd33dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
