<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mens Shirt</name>
   <tag></tag>
   <elementGuidId>db5f9722-c1c4-410e-963e-f3c9876c2c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardLink--8670368694440</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CardLink--8670368694440']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Men's Shirt Sale&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a29358c-e388-4403-85dc-e030717df2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/mens-shirt?_pos=1&amp;_sid=936860c1e&amp;_ss=r</value>
      <webElementGuid>f3cc9370-5872-4270-b95c-9140f9b245ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink--8670368694440</value>
      <webElementGuid>e26b0dfa-dfc6-452c-9de8-37969f7c3d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>440d3c97-0078-4c7b-ba64-dacbc40c9589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink--8670368694440 Badge--8670368694440</value>
      <webElementGuid>f6a3de33-3a1c-47fb-816b-caf673468953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Men's Shirt
            </value>
      <webElementGuid>d2980e6c-5b57-4e9e-9de0-9cf1b4592bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink--8670368694440&quot;)</value>
      <webElementGuid>228ddbbe-b9ac-4299-b13a-5c3f5e1aabf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink--8670368694440']</value>
      <webElementGuid>e157c234-d9d2-45d8-ba98-1e36cecc1979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title--8670368694440']/a</value>
      <webElementGuid>5693401b-980a-4d0f-939e-cf133e9a4c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale'])[1]/following::a[1]</value>
      <webElementGuid>d30f53da-3fcc-4956-a13e-e3b970707c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[1]/preceding::a[1]</value>
      <webElementGuid>ffc1cc1e-5d39-4569-a9e1-e5d31a1f5917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 999.00'])[1]/preceding::a[1]</value>
      <webElementGuid>1d3fa865-cef5-4015-a0ee-996cb40230f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/mens-shirt?_pos=1&amp;_sid=936860c1e&amp;_ss=r')])[2]</value>
      <webElementGuid>2141efe3-87b0-45a2-9f90-95d114f4ace3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3/a</value>
      <webElementGuid>ac092fe8-6816-4083-a112-033abc7e1fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/mens-shirt?_pos=1&amp;_sid=936860c1e&amp;_ss=r' and @id = 'CardLink--8670368694440' and (text() = concat(&quot;
              Men&quot; , &quot;'&quot; , &quot;s Shirt
            &quot;) or . = concat(&quot;
              Men&quot; , &quot;'&quot; , &quot;s Shirt
            &quot;))]</value>
      <webElementGuid>f9d8d324-db79-4175-a376-dad46dfff059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
