<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADIDAS  KIDS STAN SMITH</name>
   <tag></tag>
   <elementGuidId>2bee548b-76a9-49bd-a172-30308082edb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardLink-template--18610480611551__featured_collection-8834481881311</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CardLink-template--18610480611551__featured_collection-8834481881311']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ADIDAS | KID'S STAN SMITH Sale&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d56ce50b-8f69-47ff-b16e-6a9cf6cc83a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/adidas-kids-stan-smith</value>
      <webElementGuid>526edd1f-10f4-453a-8ca2-f737d85230d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink-template--18610480611551__featured_collection-8834481881311</value>
      <webElementGuid>dc02a97a-fcf4-47d3-997b-f7e1839a9081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>91054ee9-c950-4d98-9ddb-43433701e5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink-template--18610480611551__featured_collection-8834481881311 Badge-template--18610480611551__featured_collection-8834481881311</value>
      <webElementGuid>8eeb95d8-ba03-4e10-a041-3cdc9ec865f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              ADIDAS | KID'S STAN SMITH
            </value>
      <webElementGuid>4527fad9-3090-42b6-9609-b70cef7d41ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink-template--18610480611551__featured_collection-8834481881311&quot;)</value>
      <webElementGuid>f8310006-8073-4d7c-b6d2-6698e0f8d11d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink-template--18610480611551__featured_collection-8834481881311']</value>
      <webElementGuid>2b1d52ba-7d80-49d8-ab3d-419e8dc1aee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title-template--18610480611551__featured_collection-8834481881311']/a</value>
      <webElementGuid>fde3c964-7466-42de-9b0c-e48a4ff3a1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale'])[5]/following::a[1]</value>
      <webElementGuid>0e6aa0ff-92da-4c4b-ac4c-8f73c91dc898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[5]/preceding::a[1]</value>
      <webElementGuid>fc27a3f1-ebe1-4751-8ce9-7d0e7fdc2089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 72.00'])[1]/preceding::a[1]</value>
      <webElementGuid>d8cda9a0-94c5-4a5c-a71b-bdf632437526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/adidas-kids-stan-smith')])[2]</value>
      <webElementGuid>c2667bb7-d3e8-41bf-a84d-cc7f938c9f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div[2]/div/h3/a</value>
      <webElementGuid>e206f7e4-ebfe-43b3-b345-93f65648a1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/adidas-kids-stan-smith' and @id = 'CardLink-template--18610480611551__featured_collection-8834481881311' and (text() = concat(&quot;
              ADIDAS | KID&quot; , &quot;'&quot; , &quot;S STAN SMITH
            &quot;) or . = concat(&quot;
              ADIDAS | KID&quot; , &quot;'&quot; , &quot;S STAN SMITH
            &quot;))]</value>
      <webElementGuid>ac8c78be-bd26-4502-a74c-b8f760c023f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
