<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Featured</name>
   <tag></tag>
   <elementGuidId>9c1a7963-7c07-4048-922b-8d9bababb313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.title.inline-richtext.h1.scroll-trigger.animate--slide-in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collection-template--18610480611551__featured_collection']/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Featured&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>82e30459-d68f-45de-a4ac-c5defc486f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title inline-richtext h1 scroll-trigger animate--slide-in</value>
      <webElementGuid>603ebd8d-0dd5-47f4-bae0-fbaf63407c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Featured
        </value>
      <webElementGuid>19c3a195-b3bb-479c-ab92-79f504d387d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-template--18610480611551__featured_collection&quot;)/div[@class=&quot;collection__title title-wrapper title-wrapper--no-top-margin page-width&quot;]/h2[@class=&quot;title inline-richtext h1 scroll-trigger animate--slide-in&quot;]</value>
      <webElementGuid>3a525305-5465-44d6-b271-87f31ad326df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-template--18610480611551__featured_collection']/div/h2</value>
      <webElementGuid>a8740e9d-5246-44d6-a8df-c8598f6d40a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explore Threads'])[1]/following::h2[1]</value>
      <webElementGuid>c9a62deb-8281-4bec-821a-641e75a6a306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uncover your wardrobe essentials'])[1]/following::h2[1]</value>
      <webElementGuid>51ec78f4-96ad-466b-b22f-39f33746fc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADIDAS | CLASSIC BACKPACK'])[1]/preceding::h2[1]</value>
      <webElementGuid>3836fd78-cfcc-4c2f-935b-8b75898d7dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale'])[1]/preceding::h2[1]</value>
      <webElementGuid>bb2c2520-e148-45e3-bd73-9a9df2d16d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Featured']/parent::*</value>
      <webElementGuid>fe499c2f-3f91-4745-81b5-c56ebcab3c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/h2</value>
      <webElementGuid>f9976fd9-2ae9-4409-bc51-1c2d0b76cbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '
          Featured
        ' or . = '
          Featured
        ')]</value>
      <webElementGuid>e85ce9f1-4f2d-4217-9408-3381d3c50f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
