<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>d89c8bb5-5832-46e5-9aa3-697dab24526f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.coc-button.coc-cancel-button.coc-cancel-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-template--18610481463519__main']/div/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58cd2db1-7845-41ab-9944-915ddf80e099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coc-button coc-cancel-button coc-cancel-active</value>
      <webElementGuid>8afcd9ad-b4ce-4eb4-91dc-bc8a485e58b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-order-id</name>
      <type>Main</type>
      <value>5839981510879</value>
      <webElementGuid>5cc1d77d-55cc-4326-9fb5-c853ebcd42ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>39ed018e-b274-44e7-8206-19c070b3039c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--18610481463519__main&quot;)/div[@class=&quot;customer order section-template--18610481463519__main-padding&quot;]/div[2]/div[1]/div[@class=&quot;coc-d-flex coc-flex-wrap coc-gap-2 coc-py-2&quot;]/button[@class=&quot;coc-button coc-cancel-button coc-cancel-active&quot;]</value>
      <webElementGuid>d32a1d87-a940-4a2d-b562-67e60b0ab1ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-template--18610481463519__main']/div/div[2]/div/div/button</value>
      <webElementGuid>76f72cd8-e810-4f0c-8c22-96eb7d00fb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October 29, 2024 at 5:22 am'])[1]/following::button[1]</value>
      <webElementGuid>838b0488-2566-4f13-8d66-f5cd0f582bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #1033'])[1]/following::button[1]</value>
      <webElementGuid>5b82ec07-e3d1-4caa-a548-a6a6f7843ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reorder'])[1]/preceding::button[1]</value>
      <webElementGuid>606ffaae-322f-4bf9-b5b3-be90ab9bae15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #1033'])[2]/preceding::button[2]</value>
      <webElementGuid>cf663a76-f7e9-4f22-84ca-916bdd7ae34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>0d095af5-308a-48ac-912b-48e3ea336276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>7718fb7c-c3dd-4998-9745-72d46bf5740f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>133660a1-3c8d-405a-a997-93ed4f531700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
