<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Cancel Confirmation</name>
   <tag></tag>
   <elementGuidId>3bae9b5c-3bb2-4cd2-900c-fff34431e1b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.coc-modal-header-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coc-cancel-modal']/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Cancel Confirmation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>93cc9abc-8bd5-46a3-9e6e-25f0440989e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coc-modal-header-title</value>
      <webElementGuid>f84c7bd1-a735-4694-ba23-6bcd82251886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel Confirmation</value>
      <webElementGuid>22211dcf-691c-47f7-82ec-290621914f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coc-cancel-modal&quot;)/div[@class=&quot;coc-modal&quot;]/div[@class=&quot;coc-modal-header&quot;]/h3[@class=&quot;coc-modal-header-title&quot;]</value>
      <webElementGuid>d8cd7a7b-4bad-4b6c-b238-8571b25be035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coc-cancel-modal']/div/div/h3</value>
      <webElementGuid>fe9de601-8f6d-4355-a3c0-7398cd450fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::h3[1]</value>
      <webElementGuid>4eb3b24d-0197-401c-9759-e6343be291ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed'])[1]/preceding::h3[1]</value>
      <webElementGuid>7feab7f6-c38c-416e-935d-e67a9496f8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel Confirmation']/parent::*</value>
      <webElementGuid>54c9531d-6436-4438-b0bb-6d580b67d4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>c3b3347d-784d-4990-9706-a918141ca065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Cancel Confirmation' or . = 'Cancel Confirmation')]</value>
      <webElementGuid>e6bcb0e1-814b-4644-a610-9bfa6a9fcf07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
