<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mens Shirt</name>
   <tag></tag>
   <elementGuidId>258b92a7-db91-4302-9841-c219051c949c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardLink-template--17877713846440__featured_collection-8670368694440</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CardLink-template--17877713846440__featured_collection-8670368694440']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Men's Shirt Sale&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77e3755a-eace-4318-9745-4cc06b0c7494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/mens-shirt</value>
      <webElementGuid>475845db-1304-4db4-930e-3dd137c6d0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink-template--17877713846440__featured_collection-8670368694440</value>
      <webElementGuid>624d52ad-9b7f-4fcb-8d5e-70fb2180438f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>e1ccd717-77bd-4485-a463-93d7f5d5012c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink-template--17877713846440__featured_collection-8670368694440 Badge-template--17877713846440__featured_collection-8670368694440</value>
      <webElementGuid>72d4fa79-ce3b-4d11-b148-6165621f9dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Men's Shirt
            </value>
      <webElementGuid>8d5e9750-f75d-46dd-9bb4-25a4639b59ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink-template--17877713846440__featured_collection-8670368694440&quot;)</value>
      <webElementGuid>c04f29c9-a52b-4dc9-b730-757dab2bfeb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink-template--17877713846440__featured_collection-8670368694440']</value>
      <webElementGuid>9d14ba4e-05b3-4168-8f45-d6bb73519ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title-template--17877713846440__featured_collection-8670368694440']/a</value>
      <webElementGuid>57b9afd8-0a23-42d0-998f-d9a835d08789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale'])[3]/following::a[1]</value>
      <webElementGuid>34b99b70-9895-4c9a-80a4-0d763b44f676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[5]/preceding::a[1]</value>
      <webElementGuid>75ae65ed-8069-42bd-ac16-1ad8202d1a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 999.00'])[1]/preceding::a[1]</value>
      <webElementGuid>11c4c7f4-da61-4f80-95b8-86becf1632b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/mens-shirt')])[2]</value>
      <webElementGuid>07d8a84b-6739-4ce4-966c-5e5cce284b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div[2]/div/h3/a</value>
      <webElementGuid>8a240c64-4c1e-4b2a-aed1-7dc34ddea777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/mens-shirt' and @id = 'CardLink-template--17877713846440__featured_collection-8670368694440' and (text() = concat(&quot;
              Men&quot; , &quot;'&quot; , &quot;s Shirt
            &quot;) or . = concat(&quot;
              Men&quot; , &quot;'&quot; , &quot;s Shirt
            &quot;))]</value>
      <webElementGuid>25904903-6e0b-45a8-9634-39153bb515d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
