<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_customeremail</name>
   <tag></tag>
   <elementGuidId>a82074a2-bbbe-4021-bb3e-660be668b536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RegisterForm-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RegisterForm-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#RegisterForm-email</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee3cd9a0-6c0b-4956-8a40-97c50a39986f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>83ec0227-adb3-4110-80b3-30b0eb6e7c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[email]</value>
      <webElementGuid>e74656ad-10e5-4f5b-9d0b-9499c38adbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegisterForm-email</value>
      <webElementGuid>5f8cf5dd-0332-49c4-b1dd-ed1dcbc585b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eb04f322-2d88-4906-a0fe-fb47d4fc4187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1de28fcc-2e2f-485a-9c05-7b06dd8ccad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ada5308b-a87a-48cd-9928-6a5e33e8abc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5334bc0-28ef-4cf0-9704-8e51e80a99a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>415eae04-e5e7-4a16-9807-91375be3171d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegisterForm-email&quot;)</value>
      <webElementGuid>195e6c9e-2e8c-44f1-abad-5d96969b71d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RegisterForm-email']</value>
      <webElementGuid>933ca8d4-1c71-47fb-8268-c22dc05f3eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_customer']/div[3]/input</value>
      <webElementGuid>79c7eca2-969e-4378-a95e-5cb3036494b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/input</value>
      <webElementGuid>36aeeb36-a7b8-41e5-8df0-183ef84f202b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'customer[email]' and @id = 'RegisterForm-email' and @placeholder = 'Email']</value>
      <webElementGuid>92d13ba4-e1f4-44f3-92e1-205cf4599eb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
