<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create account_customerfirst_name</name>
   <tag></tag>
   <elementGuidId>076e9849-69ca-4a5b-9b9b-c19ae3741da4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RegisterForm-FirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RegisterForm-FirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;First name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bed34b7-88ab-454d-b131-782364f39f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c930774-e032-4eaf-b118-cee5e5d3d296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[first_name]</value>
      <webElementGuid>e4b4fa03-8c04-406a-a69a-5d8bb1807588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegisterForm-FirstName</value>
      <webElementGuid>536c80ba-9e53-4fe7-8a40-088e81a23792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>3c512ee2-4e27-4c79-a09f-52e870ad5cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>980ecc87-23d2-46bf-8993-4469e774648a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegisterForm-FirstName&quot;)</value>
      <webElementGuid>dca85fa9-eec0-43cc-baf3-0e47806cc34a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RegisterForm-FirstName']</value>
      <webElementGuid>14d8d8f2-2316-4a46-966e-0c170882f5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_customer']/div/input</value>
      <webElementGuid>b6251135-870a-4cd0-b25a-6cf6932dfa3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/form/div/input</value>
      <webElementGuid>3c4cb2e8-7468-4630-9a17-5987643c8cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customer[first_name]' and @id = 'RegisterForm-FirstName' and @placeholder = 'First name']</value>
      <webElementGuid>bbb531a6-5f5b-494a-811b-5258bd340c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
