<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>c6a4c2d4-f222-4a54-9cfd-607314b49045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.coc-button.coc-cancel-button.coc-cancel-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shopify-section-template--18610481463519__main']/div/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>430b5f2b-3cc0-4576-b635-f21d0b1df808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coc-button coc-cancel-button coc-cancel-active</value>
      <webElementGuid>801c5c74-ba97-4bc6-a5b7-62f5afe40a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-order-id</name>
      <type>Main</type>
      <value>5839999598815</value>
      <webElementGuid>fcc495c3-82c8-4d1a-8654-d81bbb0f1f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>89aa5590-f6de-405a-aa52-e78bd37bf060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shopify-section-template--18610481463519__main&quot;)/div[@class=&quot;customer order section-template--18610481463519__main-padding&quot;]/div[2]/div[1]/div[@class=&quot;coc-d-flex coc-flex-wrap coc-gap-2 coc-py-2&quot;]/button[@class=&quot;coc-button coc-cancel-button coc-cancel-active&quot;]</value>
      <webElementGuid>c8ae0b4b-8a9a-48f8-845b-fe535b43a92a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shopify-section-template--18610481463519__main']/div/div[2]/div/div/button</value>
      <webElementGuid>579c0be6-cfee-4c3a-bec6-8729830c2724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October 29, 2024 at 5:54 am'])[1]/following::button[1]</value>
      <webElementGuid>8e4efd81-5bca-4a0e-b9e8-3283081aca91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #1035'])[1]/following::button[1]</value>
      <webElementGuid>3ddfcc06-cbaa-4c9a-977e-d0ac515c8136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reorder'])[1]/preceding::button[1]</value>
      <webElementGuid>d09fac4c-9b2a-4dd0-aae3-1f0c373cf52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #1035'])[2]/preceding::button[2]</value>
      <webElementGuid>cbcf5a23-17c6-4b43-af54-c400d185411c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>f7a393b6-5dcd-4854-b475-b2c2c70f24ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>0353ca99-5535-4f4b-949e-30106398335e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Cancel' or . = 'Cancel')]</value>
      <webElementGuid>68d60461-4cee-41c8-bccf-6a582f0d48be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
