<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customize</name>
   <tag></tag>
   <elementGuidId>1646e457-b9c9-4117-b4ae-8a2be2a99b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.Polaris-Button.Polaris-Button--pressable.Polaris-Button--variantPrimary.Polaris-Button--sizeMedium.Polaris-Button--textAlignCenter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div[3]/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Customize Dawn&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>067dacda-f945-42a4-b287-f5caf70f2f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://admin.shopify.com/store/threads0/themes/145737285855/editor</value>
      <webElementGuid>f0ed5262-3dc3-406b-8739-239055c4e5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-polaris-unstyled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>07ec8091-5bd3-4dc8-98ab-2a79b1679a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Polaris-Button Polaris-Button--pressable Polaris-Button--variantPrimary Polaris-Button--sizeMedium Polaris-Button--textAlignCenter</value>
      <webElementGuid>013d2db4-cf0a-41e3-a45d-f63dfe20fa93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Customize Dawn</value>
      <webElementGuid>eb27abf3-633e-443d-86ea-8fe05b531f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customize</value>
      <webElementGuid>8c207415-4beb-4281-b9a2-467849f1cc08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;Online-Store-UI-AppProvider_gpbc5&quot;]/div[@class=&quot;UYl7w kbVb4&quot;]/div[@class=&quot;Polaris-Page&quot;]/div[2]/div[@class=&quot;Polaris-BlockStack&quot;]/div[@class=&quot;Polaris-LegacyStack Polaris-LegacyStack--distributionFill&quot;]/div[@class=&quot;Polaris-LegacyStack__Item&quot;]/div[@class=&quot;Polaris-Layout&quot;]/div[@class=&quot;Polaris-Layout__Section Polaris-Layout__Section--fullWidth&quot;]/div[@class=&quot;Polaris-ShadowBevel&quot;]/div[@class=&quot;Polaris-Box&quot;]/div[@class=&quot;Polaris-Box&quot;]/div[@class=&quot;tIlKz&quot;]/div[3]/div[@class=&quot;ra5dh wBFi_ XGsF9&quot;]/div[@class=&quot;Polaris-ButtonGroup&quot;]/div[@class=&quot;Polaris-ButtonGroup__Item&quot;]/a[@class=&quot;Polaris-Button Polaris-Button--pressable Polaris-Button--variantPrimary Polaris-Button--sizeMedium Polaris-Button--textAlignCenter&quot;]</value>
      <webElementGuid>5e531cd8-63d4-4993-9de7-46707f2aef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Thread_Webshop/Banner/Page_Threads  Themes  Shopify/iframe_Online Store_fe56d741-3ec3-491d-b2e4_176b02</value>
      <webElementGuid>207cbb05-a9f6-4958-910b-1f7bd2121102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div[3]/div/div[2]/div[2]/a</value>
      <webElementGuid>727ada98-be9c-4d87-a570-943fd84f6327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current theme'])[1]/following::a[1]</value>
      <webElementGuid>7dd1abf2-afd7-46e1-a3b5-5163795096b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theme library'])[1]/preceding::a[1]</value>
      <webElementGuid>792c644d-3d43-4a03-9a03-ebe176a1d19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://admin.shopify.com/store/threads0/themes/145737285855/editor')]</value>
      <webElementGuid>5719b3cb-5883-4d74-803a-a03af0aacaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>21ca8c72-1008-47bc-bae4-a2a45be8d319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://admin.shopify.com/store/threads0/themes/145737285855/editor' and (text() = 'Customize' or . = 'Customize')]</value>
      <webElementGuid>2315773c-1a7c-4f8e-8098-2c558286be82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
