<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_customerlast_name</name>
   <tag></tag>
   <elementGuidId>41761ff7-9ded-4197-882e-4fda77085f1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RegisterForm-LastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RegisterForm-LastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc0087d9-1b08-4950-bb9f-b738672b0de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8f6624d-2131-4ba4-9791-0645f39a7288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[last_name]</value>
      <webElementGuid>f7490774-4fd6-416f-ad78-91e3eec2a196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegisterForm-LastName</value>
      <webElementGuid>126e3350-38da-4c1a-8372-65981f056f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>family-name</value>
      <webElementGuid>8cb88a15-df50-492c-8c43-5c464b6d3df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>abe4b1bb-0780-4440-b1f9-ec7b4fbe7a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegisterForm-LastName&quot;)</value>
      <webElementGuid>4743ec9e-a8b9-41a0-8f2f-36b6b5581eff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RegisterForm-LastName']</value>
      <webElementGuid>6d76029f-dd25-4cf9-a24d-2587a5d07ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create_customer']/div[2]/input</value>
      <webElementGuid>2fed9ed2-89a5-4803-9ead-fb6fb6e8d90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5b22af5b-e585-41ea-b3cd-42e880ac304f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customer[last_name]' and @id = 'RegisterForm-LastName' and @placeholder = 'Last name']</value>
      <webElementGuid>6f1af6e3-eccb-44fc-8567-ac6f072e16ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
