<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ADIDAS  CLASSIC BACKPACK</name>
   <tag></tag>
   <elementGuidId>c364f312-77fb-43d6-8f2b-9ce016a173d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CardLink-template--18610480611551__featured_collection-8834482045151']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CardLink-template--18610480611551__featured_collection-8834482045151</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ADIDAS | CLASSIC BACKPACK Sale&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb1b8883-e293-4c92-a638-da914730ef99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/adidas-classic-backpack</value>
      <webElementGuid>9f6d4203-6057-4d9f-9250-72b71555014f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink-template--18610480611551__featured_collection-8834482045151</value>
      <webElementGuid>8d1320d2-4f34-451d-a762-b6ee26e863db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>ad9bf7db-580f-4c02-86b8-b588e0786c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink-template--18610480611551__featured_collection-8834482045151 Badge-template--18610480611551__featured_collection-8834482045151</value>
      <webElementGuid>585858ea-68b8-48e9-9782-2da71e8221c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              ADIDAS | CLASSIC BACKPACK
            </value>
      <webElementGuid>3eddd9f6-d1ad-48d9-a62d-3a7ac0d28f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink-template--18610480611551__featured_collection-8834482045151&quot;)</value>
      <webElementGuid>cb5dad61-cc6f-4e02-98f8-e4c8bac15e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink-template--18610480611551__featured_collection-8834482045151']</value>
      <webElementGuid>1c5ec5a3-f32b-4328-a7ab-c132d8a02d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title-template--18610480611551__featured_collection-8834482045151']/a</value>
      <webElementGuid>240619ac-7b46-4555-b37e-4a3c64622898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ADIDAS | CLASSIC BACKPACK')])[2]</value>
      <webElementGuid>cd92f17d-79f6-4fdb-b033-286f514f1782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sale'])[1]/following::a[1]</value>
      <webElementGuid>1a6f1085-ad0d-48f1-a04b-7e285eb405a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADIDAS | CLASSIC BACKPACK'])[1]/following::a[1]</value>
      <webElementGuid>e758f801-c8eb-4ae6-90a4-ed1e69a9fe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[1]/preceding::a[1]</value>
      <webElementGuid>1465dd2e-55b8-4407-a37f-23ece18f7bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 56.00'])[1]/preceding::a[1]</value>
      <webElementGuid>b53c62cc-6c06-4287-b777-3675d99df527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/adidas-classic-backpack')])[2]</value>
      <webElementGuid>4ab18ea5-ef52-4e75-8671-e309d173bf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3/a</value>
      <webElementGuid>dfcb51b0-c729-4494-bc05-5702e23fa23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/adidas-classic-backpack' and @id = 'CardLink-template--18610480611551__featured_collection-8834482045151' and (text() = '
              ADIDAS | CLASSIC BACKPACK
            ' or . = '
              ADIDAS | CLASSIC BACKPACK
            ')]</value>
      <webElementGuid>a559621d-739e-4dd8-93de-49cca561a392</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
