<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Catalog</name>
   <tag></tag>
   <elementGuidId>73ed6674-a505-4e03-8e40-36b28fe337c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#HeaderMenu-catalog > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='HeaderMenu-catalog']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Catalog&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa38318d-c3fe-47fc-8179-ef5d93d75d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Catalog</value>
      <webElementGuid>df11b7c1-a6f1-41c7-bf99-fb02af2e69bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HeaderMenu-catalog&quot;)/span[1]</value>
      <webElementGuid>9ab69772-e5f5-4bba-a996-6a20f1571537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='HeaderMenu-catalog']/span</value>
      <webElementGuid>5777fc3c-b62d-4d09-949c-6d0e1a4dc5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/following::span[1]</value>
      <webElementGuid>0b297968-71ce-407a-ad0d-a6ed43193106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/following::span[2]</value>
      <webElementGuid>7556d419-c58c-4e72-a2a2-d1dd3f85d0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[2]/preceding::span[1]</value>
      <webElementGuid>61ab099b-59d3-4786-aac5-8125d1adece8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::span[5]</value>
      <webElementGuid>ad626aad-5364-4741-9c7f-154e7a84f1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a/span</value>
      <webElementGuid>cc8cd1a8-0723-42d3-89c7-5e8f1ddbfdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Catalog' or . = 'Catalog')]</value>
      <webElementGuid>3e73af24-4a31-4ce7-bcf0-d45b37055d09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
