<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONVERSE  CHUCK TAYLOR ALL STAR II HI</name>
   <tag></tag>
   <elementGuidId>29fcb186-e76a-4674-b1f7-0dd80a4936db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardLink-template--18610480578783__product-grid-8834481717471</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='CardLink-template--18610480578783__product-grid-8834481717471']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;CONVERSE | CHUCK TAYLOR ALL STAR II HI&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9e7cfef-5a4b-4e44-9627-4a85eb984ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/converse-chuck-taylor-all-star-ii-hi</value>
      <webElementGuid>a03cd9b7-7b04-4d97-b327-a8836ef0797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481717471</value>
      <webElementGuid>2c04c1e8-2530-46fa-bba6-830055596863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-unstyled-link</value>
      <webElementGuid>38e5ef9b-a48e-46f7-8a4a-74460048518d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CardLink-template--18610480578783__product-grid-8834481717471 Badge-template--18610480578783__product-grid-8834481717471</value>
      <webElementGuid>a15d89e9-1302-4578-bc80-c2f3d29a74c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              CONVERSE | CHUCK TAYLOR ALL STAR II HI
            </value>
      <webElementGuid>3a997275-2152-4d12-8625-54ded71494a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardLink-template--18610480578783__product-grid-8834481717471&quot;)</value>
      <webElementGuid>29cff1a6-281d-4059-b8af-4a24e963939f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='CardLink-template--18610480578783__product-grid-8834481717471']</value>
      <webElementGuid>18695647-3c78-4ab6-abf6-1170dde8ac0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h3[@id='title-template--18610480578783__product-grid-8834481717471']/a</value>
      <webElementGuid>a2ab495f-aa7d-4a3f-88c5-e21cf6912bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'CONVERSE | CHUCK TAYLOR ALL STAR II HI')])[2]</value>
      <webElementGuid>d165f99a-d1e6-4097-a497-6b33f52df69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONVERSE | CHUCK TAYLOR ALL STAR II HI'])[1]/following::a[1]</value>
      <webElementGuid>5ff7ee7d-ce5a-4617-840d-532cd11287ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regular price'])[11]/preceding::a[1]</value>
      <webElementGuid>f2aa839b-fc4c-46f2-bf38-f39b365973c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs. 140.00'])[1]/preceding::a[1]</value>
      <webElementGuid>11c79a1e-99fe-4538-afb5-ff357b628d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/products/converse-chuck-taylor-all-star-ii-hi')])[2]</value>
      <webElementGuid>9f985694-0fff-48ec-a0c3-3b01c670bbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div/div[2]/div/h3/a</value>
      <webElementGuid>b25a7ff6-5ce8-4853-a8a1-68f5ab7e62d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/converse-chuck-taylor-all-star-ii-hi' and @id = 'CardLink-template--18610480578783__product-grid-8834481717471' and (text() = '
              CONVERSE | CHUCK TAYLOR ALL STAR II HI
            ' or . = '
              CONVERSE | CHUCK TAYLOR ALL STAR II HI
            ')]</value>
      <webElementGuid>495a40b6-2805-4467-816e-f1386e2691d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
