<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Final TestSuit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5fceac7b-070a-4c7e-91e9-73b33b4a9bb7</testSuiteGuid>
   <testCaseLink>
      <guid>63cfd8c1-e884-4fee-9c11-1467f6185c56</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/1 Registration/TC-73,31-Verify the registration</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98f957d9-3a0d-4606-9529-6600bb81b767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>625c7296-bc2b-4680-adb8-1450e3181c0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f7556b0-905a-4ad9-b93d-f74f6216c611</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d52037e2-7572-4a83-a115-1bd086e6f352</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>324af5ff-95f1-40ac-a70a-dc37319aea77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a814d51-4d96-4cd1-bc79-bc6be743f943</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5c5b30f-5978-4362-a25b-6a9d7bfc390f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7749ea59-c70e-48b5-bee8-9f9971f65078</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/2 Login/Verify Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21615694-7d92-40dd-890b-5b224e677076</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>371f663e-8c7d-4460-8f2e-f310a87f641a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0826e835-c329-4881-a910-528f50c8f5de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef815caf-b6c0-47d9-a0be-c2a204b27707</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c2dfb30-f858-473f-8970-dea46e7b2b1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d2e396e-b361-4300-9571-c9447b9a670a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98486c71-6e6d-43ec-a4e5-c99ce4508911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8075396f-6833-49cc-864c-2387d66d47aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b80a9bf-ef63-4b32-96c7-aced3102e174</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78057428-ed23-4725-a90f-95a9e573ae61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/3 Homepage/TC-3,66-Verify Seach Bar</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5c7f15c-f9e6-40bd-a10f-d89a72108eb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a97d9ace-260c-40c0-be04-ef69b48a4155</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cad12ccc-742a-4977-b5fb-eb743147b739</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>844169c2-42e0-43bd-9101-80883a77a538</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b4bb96d-7282-4f60-8293-56134799a1a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54129da3-03b0-4d0c-9695-aeb6b1ed4dc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/3 Homepage/TC-672-Verify the Social media button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7ca52ec8-9cdc-4352-b7f0-c33fa08aef9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/3 Homepage/TC-89,11-Verify Home page elements</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c6478ac8-64cd-40c4-8ac4-ed3ca65c8e0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/4 Search/TC-112, 169, 143-Verify Search Scenario</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c172dbf5-b4dd-4c99-bebe-1fcb8359210f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d08b3b5-da25-47c2-adec-cb196143192e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2257a8ec-b577-430d-80a7-ad1d253b17df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/5 Shopping Cart/TC-157 Verify the cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c0a833fe-f3c2-4094-835c-5517a5309fc7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/5 Shopping Cart/TC-309-Verify Promo code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a2536172-fe66-4662-afe5-04f312f943c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/6 Checkout/TC-178,404,305-Verify checkout scenario</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62154826-dbc1-48bb-899e-ea78a403cde7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01338883-4f61-4f2d-9028-714ec82029e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>651f0497-6151-404c-854b-3a2511830b57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/6 Checkout/TC-Verify Shipping method</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0ffe9e7e-5e70-4ef1-b8ca-5fa57e10292f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/7 My Account/TC-165-Verify Edit Address</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>005e35ef-3f5a-4e1f-aa79-fca0547051b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/7 My Account/TC-308,307-Verify the Credit Card details</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ef779a9b-1989-441c-98bc-f79138691ace</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/8 Order Details/Product Subscription</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4d15e08d-1b22-4e6c-932c-5f6dee012159</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/8 Order Details/TC-570, Verify Cancle Order</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81281e27-3af6-4b2d-82a8-2c33b422959b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90f2a417-2628-47f6-8543-1921fc4ac2cb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e882aae-0616-4e32-a0e0-9542ffb1993a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/8 Order Details/TC-575, Verify Reorder</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e1a1fa87-5ce6-4e53-b5a0-cbd5050a89e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/9 Wishlist/TC-588 TC-65 TC-605 Add item to Wishlist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5b1ab17-e221-4ff7-8d27-676db197e81d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d007ed15-ef06-4961-a764-ba4d5511d44a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab191dba-4df1-4136-a498-a86d0c347d6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/9 Wishlist/TC-593-Verify Wishlist to Cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>85d8ff5e-ec94-46e1-a7a3-d593c39b8f52</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/Product Details Page/TC-176, Verify item by Colour and Size</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67a12d96-4399-4021-ae62-c5846322d61d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bac7d169-542e-4111-ad9a-3a8f93ef60fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abe5323b-96e2-44fc-ab95-e22677f4fbb6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e8fc13e-a046-45e7-b07e-b13b9acd5022</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/Product Details Page/TC-601, Verify item to cart when not login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>dfc2d31e-d542-49d5-85c0-b3f546210bc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/3 Homepage/Homepage-Banner/Verify Banner title</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>13dd0c6d-d94a-49af-bf2f-fbb08c9a787b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Threads_Webshop/3 Homepage/Homepage-Banner/Reset the Banner</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
